// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"github.com/pancake-lee/pgo/internal/pkg/db"
	"github.com/pancake-lee/pgo/internal/pkg/db/model"
	"github.com/pancake-lee/pgo/internal/pkg/perr"
	"github.com/pancake-lee/pgo/pkg/papp"
)

type TaskDO = model.Task

type taskDAO struct{}

var TaskDAO taskDAO

func (*taskDAO) Add(ctx *papp.AppCtx, task *TaskDO) error {
	if task == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().Task
	err := q.WithContext(ctx).Create(task)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*taskDAO) GetAll(ctx *papp.AppCtx,
) (taskList []*TaskDO, err error) {
	q := db.GetQuery().Task
	taskList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return taskList, nil
}

func (*taskDAO) GetByIndex(ctx *papp.AppCtx,
IDList []int32,
) ([]*TaskDO, error) {
	q := db.GetQuery().Task
	do := q.WithContext(ctx)

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*taskDAO) UpdateByID(ctx *papp.AppCtx, do *TaskDO) error {
	if do.ID == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().Task
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*taskDAO) DelByID(ctx *papp.AppCtx, idx1 int32) error {
	if idx1 == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().Task
	_, err := q.WithContext(ctx).Where(q.ID.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*taskDAO) DelByIDList(ctx *papp.AppCtx, idx1List []int32) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().Task
	_, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*taskDAO) GetByID(ctx *papp.AppCtx, idx1 int32,
) (task *TaskDO, err error) {
	if idx1 == 0 {
		return task, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().Task
	task, err = q.WithContext(ctx).
		Where(q.ID.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return task, nil
}

func (*taskDAO) GetByIDList(ctx *papp.AppCtx, idx1List []int32,
) (taskMap map[int32]*TaskDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().Task
	l, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	taskMap = make(map[int32]*TaskDO)
	for _, i := range l {
		taskMap[i.ID] = i
	}
	return taskMap, nil
}

