// Code generated by tools/genCURD. DO NOT EDIT.

package service

import (
	"context"
	"time"

	"github.com/pancake-lee/pgo/api"
	"github.com/pancake-lee/pgo/internal/userService/data"
	"github.com/pancake-lee/pgo/pkg/plogger"
)

func DO2DTO_UserRole(do *data.UserRoleDO) *api.UserRoleInfo {
	if do == nil {
		return nil
	}
	return &api.UserRoleInfo{
		ID:         do.ID,
		CreateTime: do.CreateTime.Unix(),
		CreateUser: do.CreateUser,
		UpdateTime: do.UpdateTime.Unix(),
		UpdateUser: do.UpdateUser,
		ProjID:     do.ProjID,
		RoleName:   do.RoleName,
		IsDefault:  do.IsDefault,
	}
}
func DTO2DO_UserRole(dto *api.UserRoleInfo) *data.UserRoleDO {
	if dto == nil {
		return nil
	}
	return &data.UserRoleDO{
		ID:         dto.ID,
		CreateTime: time.Unix(dto.CreateTime, 0),
		CreateUser: dto.CreateUser,
		UpdateTime: time.Unix(dto.UpdateTime, 0),
		UpdateUser: dto.UpdateUser,
		ProjID:     dto.ProjID,
		RoleName:   dto.RoleName,
		IsDefault:  dto.IsDefault,
	}
}

func (s *UserCURDServer) AddUserRole(
	ctx context.Context, req *api.AddUserRoleRequest,
) (resp *api.AddUserRoleResponse, err error) {
	if req.UserRole == nil {
		return nil, api.ErrorInvalidArgument("")
	}
	newData := DTO2DO_UserRole(req.UserRole)

	err = data.UserRoleDAO.Add(ctx, newData)
	if err != nil {
		return nil, plogger.LogErr(err)
	}

	plogger.Debugf("AddUserRole: %v", newData.ID)

	resp = new(api.AddUserRoleResponse)
	resp.UserRole = DO2DTO_UserRole(newData)
	return resp, nil
}

func (s *UserCURDServer) GetUserRoleList(
	ctx context.Context, req *api.GetUserRoleListRequest,
) (resp *api.GetUserRoleListResponse, err error) {

	var dataList []*data.UserRoleDO

	if len(req.IDList) != 0 {
		plogger.Debugf("GetUserRoleList: %v", req.IDList)

		dataMap, err := data.UserRoleDAO.GetByIDList(ctx, req.IDList)
		if err != nil {
			return nil, plogger.LogErr(err)
		}
		for _, d := range dataMap {
			dataList = append(dataList, d)
		}
	} else {

		dataList, err = data.UserRoleDAO.GetAll(ctx)
		if err != nil {
			return nil, plogger.LogErr(err)
		}

	}

	plogger.Debugf("GetUserRoleList resp len %v", len(dataList))

	resp = new(api.GetUserRoleListResponse)
	resp.UserRoleList = make([]*api.UserRoleInfo, 0, len(dataList))
	for _, data := range dataList {
		resp.UserRoleList = append(resp.UserRoleList, DO2DTO_UserRole(data))
	}
	return resp, nil
}

func (s *UserCURDServer) UpdateUserRole(
	ctx context.Context, req *api.UpdateUserRoleRequest,
) (resp *api.UpdateUserRoleResponse, err error) {
	if req.UserRole == nil {
		return nil, api.ErrorInvalidArgument("")
	}

	do := DTO2DO_UserRole(req.UserRole)
	err = data.UserRoleDAO.UpdateByID(ctx, do)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	plogger.Debugf("UpdateUserRole %v", req.UserRole.ID)

	resp = new(api.UpdateUserRoleResponse)
	d, err := data.UserRoleDAO.GetByID(ctx, req.UserRole.ID)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	resp.UserRole = DO2DTO_UserRole(d)
	return resp, nil
}

func (s *UserCURDServer) DelUserRoleByIDList(
	ctx context.Context, req *api.DelUserRoleByIDListRequest,
) (resp *api.Empty, err error) {
	if len(req.IDList) == 0 {
		return nil, nil
	}
	err = data.UserRoleDAO.DelByIDList(ctx, req.IDList)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	plogger.Debugf("DelUserRoleByIDList %v", req.IDList)
	return nil, nil
}
