// Code generated by tools/genCURD. DO NOT EDIT.

package service

import "time"

import (
	"context"

	"github.com/pancake-lee/pgo/api"
	"github.com/pancake-lee/pgo/internal/userService/data"
	"github.com/pancake-lee/pgo/pkg/plogger"
)

func DO2DTO_UserProjectAssoc(do *data.UserProjectAssocDO) *api.UserProjectAssocInfo {
	if do == nil {
		return nil
	}
	return &api.UserProjectAssocInfo{
        ID: do.ID,
        CreateTime: do.CreateTime.Unix(),
        CreateUser: do.CreateUser,
        UserID: do.UserID,
        ProjID: do.ProjID,
	}
}
func DTO2DO_UserProjectAssoc(dto *api.UserProjectAssocInfo) *data.UserProjectAssocDO {
	if dto == nil {
		return nil
	}
	return &data.UserProjectAssocDO{
        ID: dto.ID,
        CreateTime: time.Unix(dto.CreateTime, 0),
        CreateUser: dto.CreateUser,
        UserID: dto.UserID,
        ProjID: dto.ProjID,
	}
}

func (s *UserCURDServer) AddUserProjectAssoc(
	ctx context.Context, req *api.AddUserProjectAssocRequest,
) (resp *api.AddUserProjectAssocResponse, err error) {
	if req.UserProjectAssoc == nil {
		return nil, api.ErrorInvalidArgument("")
	}
	newData := DTO2DO_UserProjectAssoc(req.UserProjectAssoc)

	err = data.UserProjectAssocDAO.Add(ctx, newData)
	if err != nil {
		return nil, plogger.LogErr(err)
	}

	plogger.Debugf("AddUserProjectAssoc: %v", newData.ID)

	resp = new(api.AddUserProjectAssocResponse)
	resp.UserProjectAssoc = DO2DTO_UserProjectAssoc(newData)
	return resp, nil
}

func (s *UserCURDServer) GetUserProjectAssocList(
	ctx context.Context, req *api.GetUserProjectAssocListRequest,
) (resp *api.GetUserProjectAssocListResponse, err error) {

	var dataList []*data.UserProjectAssocDO

	if len(req.IDList) != 0 {
		plogger.Debugf("GetUserProjectAssocList: %v", req.IDList)

		dataList, err = data.UserProjectAssocDAO.GetByIndex(ctx,
            req.IDList,
		)
		if err != nil {
			return nil, plogger.LogErr(err)
		}
	} else {

		dataList, err = data.UserProjectAssocDAO.GetAll(ctx)
		if err != nil {
			return nil, plogger.LogErr(err)
		}

	}

	plogger.Debugf("GetUserProjectAssocList resp len %v", len(dataList))

	resp = new(api.GetUserProjectAssocListResponse)
	resp.UserProjectAssocList = make([]*api.UserProjectAssocInfo, 0, len(dataList))
	for _, data := range dataList {
		resp.UserProjectAssocList = append(resp.UserProjectAssocList, DO2DTO_UserProjectAssoc(data))
	}
	return resp, nil
}


func (s *UserCURDServer) UpdateUserProjectAssoc(
	ctx context.Context, req *api.UpdateUserProjectAssocRequest,
) (resp *api.UpdateUserProjectAssocResponse, err error) {
	if req.UserProjectAssoc == nil {
		return nil, api.ErrorInvalidArgument("")
	}

	do := DTO2DO_UserProjectAssoc(req.UserProjectAssoc)
	err = data.UserProjectAssocDAO.UpdateByID(ctx, do)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	plogger.Debugf("UpdateUserProjectAssoc %v", req.UserProjectAssoc.ID)

	resp = new(api.UpdateUserProjectAssocResponse)
	d, err := data.UserProjectAssocDAO.GetByID(ctx, req.UserProjectAssoc.ID)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	resp.UserProjectAssoc = DO2DTO_UserProjectAssoc(d)
	return resp, nil
}

func (s *UserCURDServer) DelUserProjectAssocByIDList(
	ctx context.Context, req *api.DelUserProjectAssocByIDListRequest,
) (resp *api.Empty, err error) {
	if len(req.IDList) == 0 {
		return nil, nil
	}
	err = data.UserProjectAssocDAO.DelByIDList(ctx, req.IDList)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	plogger.Debugf("DelUserProjectAssocByIDList %v", req.IDList)
	return nil, nil
}

