// Code generated by tools/genCURD. DO NOT EDIT.

package service

import "time"

import (
	"context"

	"github.com/pancake-lee/pgo/api"
	"github.com/pancake-lee/pgo/internal/userService/data"
	"github.com/pancake-lee/pgo/pkg/papp"
)

func DO2DTO_User(do *data.UserDO) *api.UserInfo {
	if do == nil {
		return nil
	}
	return &api.UserInfo{
        ID: do.ID,
        CreateTime: do.CreateTime.Unix(),
        CreateUser: do.CreateUser,
        UpdateTime: do.UpdateTime.Unix(),
        UpdateUser: do.UpdateUser,
        UserName: do.UserName,
        Password: do.Password,
        MtblRecordID: do.MtblRecordID,
        LastEditFrom: do.LastEditFrom,
	}
}
func DTO2DO_User(dto *api.UserInfo) *data.UserDO {
	if dto == nil {
		return nil
	}
	return &data.UserDO{
        ID: dto.ID,
        CreateTime: time.Unix(dto.CreateTime, 0),
        CreateUser: dto.CreateUser,
        UpdateTime: time.Unix(dto.UpdateTime, 0),
        UpdateUser: dto.UpdateUser,
        UserName: dto.UserName,
        Password: dto.Password,
        MtblRecordID: dto.MtblRecordID,
        LastEditFrom: dto.LastEditFrom,
	}
}

func (s *UserCURDServer) AddUser(
	_ctx context.Context, req *api.AddUserRequest,
) (resp *api.AddUserResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.User == nil {
		return nil, api.ErrorInvalidArgument("")
	}
	newData := DTO2DO_User(req.User)

	err = data.UserDAO.Add(ctx, newData)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}

	ctx.Log.Debugf("AddUser: %v", newData.ID)

	resp = new(api.AddUserResponse)
	resp.User = DO2DTO_User(newData)
	return resp, nil
}

func (s *UserCURDServer) GetUserList(
	_ctx context.Context, req *api.GetUserListRequest,
) (resp *api.GetUserListResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	var dataList []*data.UserDO

	if len(req.IDList) != 0 {
		ctx.Log.Debugf("GetUserList: %v", req.IDList)

		dataList, err = data.UserDAO.GetByIndex(ctx,
            req.IDList,
		)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}
	} else {

		dataList, err = data.UserDAO.GetAll(ctx)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}

	}

	ctx.Log.Debugf("GetUserList resp len %v", len(dataList))

	resp = new(api.GetUserListResponse)
	resp.UserList = make([]*api.UserInfo, 0, len(dataList))
	for _, data := range dataList {
		resp.UserList = append(resp.UserList, DO2DTO_User(data))
	}
	return resp, nil
}


func (s *UserCURDServer) UpdateUser(
	_ctx context.Context, req *api.UpdateUserRequest,
) (resp *api.UpdateUserResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.User == nil {
		return nil, api.ErrorInvalidArgument("")
	}

	do := DTO2DO_User(req.User)
	err = data.UserDAO.UpdateByID(ctx, do)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("UpdateUser %v", req.User.ID)

	resp = new(api.UpdateUserResponse)
	d, err := data.UserDAO.GetByID(ctx, req.User.ID)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	resp.User = DO2DTO_User(d)
	return resp, nil
}

func (s *UserCURDServer) DelUserByIDList(
	_ctx context.Context, req *api.DelUserByIDListRequest,
) (resp *api.Empty, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if len(req.IDList) == 0 {
		return nil, nil
	}
	err = data.UserDAO.DelByIDList(ctx, req.IDList)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("DelUserByIDList %v", req.IDList)
	return nil, nil
}

