// Code generated by tools/genCURD. DO NOT EDIT.

package service

import "time"

import (
	"context"

	"github.com/pancake-lee/pgo/api"
	"github.com/pancake-lee/pgo/internal/userService/data"
	"github.com/pancake-lee/pgo/pkg/plogger"
)

func DO2DTO_UserDeptAssoc(do *data.UserDeptAssocDO) *api.UserDeptAssocInfo {
	if do == nil {
		return nil
	}
	return &api.UserDeptAssocInfo{
        ID: do.ID,
        CreateTime: do.CreateTime.Unix(),
        CreateUser: do.CreateUser,
        UpdateTime: do.UpdateTime.Unix(),
        UpdateUser: do.UpdateUser,
        UserID: do.UserID,
        DeptID: do.DeptID,
        JobID: do.JobID,
	}
}
func DTO2DO_UserDeptAssoc(dto *api.UserDeptAssocInfo) *data.UserDeptAssocDO {
	if dto == nil {
		return nil
	}
	return &data.UserDeptAssocDO{
        ID: dto.ID,
        CreateTime: time.Unix(dto.CreateTime, 0),
        CreateUser: dto.CreateUser,
        UpdateTime: time.Unix(dto.UpdateTime, 0),
        UpdateUser: dto.UpdateUser,
        UserID: dto.UserID,
        DeptID: dto.DeptID,
        JobID: dto.JobID,
	}
}

func (s *UserCURDServer) AddUserDeptAssoc(
	ctx context.Context, req *api.AddUserDeptAssocRequest,
) (resp *api.AddUserDeptAssocResponse, err error) {
	if req.UserDeptAssoc == nil {
		return nil, api.ErrorInvalidArgument("")
	}
	newData := DTO2DO_UserDeptAssoc(req.UserDeptAssoc)

	err = data.UserDeptAssocDAO.Add(ctx, newData)
	if err != nil {
		return nil, plogger.LogErr(err)
	}

	plogger.Debugf("AddUserDeptAssoc: %v", newData.ID)

	resp = new(api.AddUserDeptAssocResponse)
	resp.UserDeptAssoc = DO2DTO_UserDeptAssoc(newData)
	return resp, nil
}

func (s *UserCURDServer) GetUserDeptAssocList(
	ctx context.Context, req *api.GetUserDeptAssocListRequest,
) (resp *api.GetUserDeptAssocListResponse, err error) {

	var dataList []*data.UserDeptAssocDO

	if len(req.IDList) != 0 {
		plogger.Debugf("GetUserDeptAssocList: %v", req.IDList)

		dataMap, err := data.UserDeptAssocDAO.GetByIDList(ctx, req.IDList)
		if err != nil {
			return nil, plogger.LogErr(err)
		}
		for _, d := range dataMap {
			dataList = append(dataList, d)
		}
	} else {

		dataList, err = data.UserDeptAssocDAO.GetAll(ctx)
		if err != nil {
			return nil, plogger.LogErr(err)
		}

	}

	plogger.Debugf("GetUserDeptAssocList resp len %v", len(dataList))

	resp = new(api.GetUserDeptAssocListResponse)
	resp.UserDeptAssocList = make([]*api.UserDeptAssocInfo, 0, len(dataList))
	for _, data := range dataList {
		resp.UserDeptAssocList = append(resp.UserDeptAssocList, DO2DTO_UserDeptAssoc(data))
	}
	return resp, nil
}


func (s *UserCURDServer) UpdateUserDeptAssoc(
	ctx context.Context, req *api.UpdateUserDeptAssocRequest,
) (resp *api.UpdateUserDeptAssocResponse, err error) {
	if req.UserDeptAssoc == nil {
		return nil, api.ErrorInvalidArgument("")
	}

	do := DTO2DO_UserDeptAssoc(req.UserDeptAssoc)
	err = data.UserDeptAssocDAO.UpdateByID(ctx, do)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	plogger.Debugf("UpdateUserDeptAssoc %v", req.UserDeptAssoc.ID)

	resp = new(api.UpdateUserDeptAssocResponse)
	d, err := data.UserDeptAssocDAO.GetByID(ctx, req.UserDeptAssoc.ID)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	resp.UserDeptAssoc = DO2DTO_UserDeptAssoc(d)
	return resp, nil
}

func (s *UserCURDServer) DelUserDeptAssocByIDList(
	ctx context.Context, req *api.DelUserDeptAssocByIDListRequest,
) (resp *api.Empty, err error) {
	if len(req.IDList) == 0 {
		return nil, nil
	}
	err = data.UserDeptAssocDAO.DelByIDList(ctx, req.IDList)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	plogger.Debugf("DelUserDeptAssocByIDList %v", req.IDList)
	return nil, nil
}



func (s *UserCURDServer) GetUserDeptAssocByUserDept(
	ctx context.Context, req *api.GetUserDeptAssocByUserDeptRequest,
) (resp *api.GetUserDeptAssocByUserDeptResponse, err error) {
	if len(req.UserIDList) == 0 && len(req.DeptIDList) == 0 {
		return nil, api.ErrorInvalidArgument("params cannot be all empty")
	}
	list, err := data.UserDeptAssocDAO.GetByUserDept(ctx, req.UserIDList, req.DeptIDList)
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	resp = new(api.GetUserDeptAssocByUserDeptResponse)
	for _, v := range list {
		resp.Data = append(resp.Data, DO2DTO_UserDeptAssoc(v))
	}
	return resp, nil
}
