// Code generated by tools/genCURD. DO NOT EDIT.

package service

import "time"

import (
	"context"

	"github.com/pancake-lee/pgo/api"
	"github.com/pancake-lee/pgo/internal/taskService/data"
	"github.com/pancake-lee/pgo/pkg/papp"
)

func DO2DTO_Task(do *data.TaskDO) *api.TaskInfo {
	if do == nil {
		return nil
	}
	return &api.TaskInfo{
        ID: do.ID,
        ParentID: do.ParentID,
        PrevID: do.PrevID,
        Task: do.Task,
        Status: do.Status,
        Estimate: do.Estimate,
        Start: do.Start.Unix(),
        End: do.End.Unix(),
        Desc: do.Desc,
        Metadata: do.Metadata,
        CreateTime: do.CreateTime.Unix(),
	}
}
func DTO2DO_Task(dto *api.TaskInfo) *data.TaskDO {
	if dto == nil {
		return nil
	}
	return &data.TaskDO{
        ID: dto.ID,
        ParentID: dto.ParentID,
        PrevID: dto.PrevID,
        Task: dto.Task,
        Status: dto.Status,
        Estimate: dto.Estimate,
        Start: time.Unix(dto.Start, 0),
        End: time.Unix(dto.End, 0),
        Desc: dto.Desc,
        Metadata: dto.Metadata,
        CreateTime: time.Unix(dto.CreateTime, 0),
	}
}

func (s *TaskCURDServer) AddTask(
	_ctx context.Context, req *api.AddTaskRequest,
) (resp *api.AddTaskResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.Task == nil {
		return nil, api.ErrorInvalidArgument("")
	}
	newData := DTO2DO_Task(req.Task)

	err = data.TaskDAO.Add(ctx, newData)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}

	ctx.Log.Debugf("AddTask: %v", newData.ID)

	resp = new(api.AddTaskResponse)
	resp.Task = DO2DTO_Task(newData)
	return resp, nil
}

func (s *TaskCURDServer) GetTaskList(
	_ctx context.Context, req *api.GetTaskListRequest,
) (resp *api.GetTaskListResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	var dataList []*data.TaskDO

	if len(req.IDList) != 0 {
		ctx.Log.Debugf("GetTaskList: %v", req.IDList)

		dataList, err = data.TaskDAO.GetByIndex(ctx,
            req.IDList,
		)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}
	} else {

		dataList, err = data.TaskDAO.GetAll(ctx)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}

	}

	ctx.Log.Debugf("GetTaskList resp len %v", len(dataList))

	resp = new(api.GetTaskListResponse)
	resp.TaskList = make([]*api.TaskInfo, 0, len(dataList))
	for _, data := range dataList {
		resp.TaskList = append(resp.TaskList, DO2DTO_Task(data))
	}
	return resp, nil
}


func (s *TaskCURDServer) UpdateTask(
	_ctx context.Context, req *api.UpdateTaskRequest,
) (resp *api.UpdateTaskResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.Task == nil {
		return nil, api.ErrorInvalidArgument("")
	}

	do := DTO2DO_Task(req.Task)
	err = data.TaskDAO.UpdateByID(ctx, do)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("UpdateTask %v", req.Task.ID)

	resp = new(api.UpdateTaskResponse)
	d, err := data.TaskDAO.GetByID(ctx, req.Task.ID)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	resp.Task = DO2DTO_Task(d)
	return resp, nil
}

func (s *TaskCURDServer) DelTaskByIDList(
	_ctx context.Context, req *api.DelTaskByIDListRequest,
) (resp *api.Empty, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if len(req.IDList) == 0 {
		return nil, nil
	}
	err = data.TaskDAO.DelByIDList(ctx, req.IDList)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("DelTaskByIDList %v", req.IDList)
	return nil, nil
}

