# wget https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64
# chmod +x docker-compose-linux-x86_64 
# mv ./docker-compose-linux-x86_64 /usr/local/bin/docker-compose

name: pgo
services:
    rocky9:
        container_name: pgo-dr9
        image: dr9:latest
        restart: on-failure:5
        command: /startup.sh
        ports:
            - 20022:22
            - 20000-20010:20000-20010
        environment:
            TZ: Asia/Shanghai
        networks:
            - pgo-net
        volumes:
            - ./config/startup.sh:/startup.sh
            - ./backend:/backend
        depends_on:
            - mysql
            - redis
            - rabbitmq
        
    mysql:
        container_name: pgo-mysql
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - 23306:3306
        networks:
            - pgo-net
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_MAX_CONNECTIONS: 10240
            TZ: Asia/Shanghai
        volumes:
            - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./mysql/data:/var/lib/mysql

    redis:
        container_name: pgo-redis
        image: redis:7.2
        restart: unless-stopped
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 26379:6379
        networks:
            - pgo-net
        volumes:
            - ./config/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/data:/data

    rabbitmq:
        container_name: pgo-rabbitmq
        image: rabbitmq:3.12-management
        restart: unless-stopped
        ports:
            - 25673:5672 
            - 25674:15672
            - 25675:25672
        networks:
            - pgo-net
        environment:
            RABBITMQ_DEFAULT_USER: pgo 
            RABBITMQ_DEFAULT_PASS: pgo
            RABBITMQ_DEFAULT_VHOST: pgo_vhost

    swagger:
        container_name: pgo-swagger
        image: swaggerapi/swagger-ui:v5.17.14
        restart: unless-stopped
        ports:
            - 28080:8080
        volumes:
            - ./openapi.yaml:/openapi.yaml
        environment:
            SWAGGER_JSON: /openapi.yaml

    # --------------------------------------------------
    # 以下都是监控组件，主要都是prometheus+grafana生态
    prometheus:
        image: prom/prometheus:v3.9.0
        container_name: pgo-prometheus
        restart: unless-stopped
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.enable-lifecycle'
        user: "root:root"  # 粗暴：使用root用户
        ports:
            - "29090:9090"
        networks:
            - pgo-net
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/data:/prometheus
        
    grafana:
        container_name: pgo-grafana
        image: grafana/grafana:12.3
        restart: unless-stopped
        user: "0:0" # 以root用户运行，方便挂载卷写入数据
        ports:
            - "23000:3000"
        networks:
            - pgo-net
        environment:
            # 初始管理员密码（首次登录后会要求修改）
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            # 持久化 Grafana 数据（仪表板、用户等）
            - ./grafana/data:/var/lib/grafana

    # --------------------------------------------------
    # 宿主机监控
    node-exporter:
        container_name: pgo-node-exporter
        image: prom/node-exporter:v1.10.2
        restart: unless-stopped
        ports:
            - 29100:9100
        networks:
            - pgo-net
        command:
            - '--path.procfs=/host/proc'          # procfs 挂载路径
            - '--path.sysfs=/host/sys'            # sysfs 挂载路径
            - '--path.rootfs=/rootfs'             # 根文件系统路径
            # 排除虚拟文件系统，避免指标干扰
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|run|var/lib/docker)($$|/)'
            # 忽略虚拟磁盘设备
            - '--collector.diskstats.device-exclude=^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\d+n\d+p)\d+$$'
            - '--collector.netdev.device-exclude=^lo$$'  # 忽略回环接口
            - '--web.listen-address=:9100'        # 监听端口
        volumes:
            # 挂载主机系统目录，用于收集系统信息
            - /proc:/host/proc:ro       # 进程信息，只读挂载
            - /sys:/host/sys:ro         # 系统信息，只读挂载
            - /:/rootfs:ro              # 根文件系统，用于收集磁盘使用
            - /run/udev:/run/udev:ro    # 设备信息
            - /dev:/host/dev:ro         # 设备文件

    # --------------------------------------------------
    # 容器监控
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.55.1
        container_name: pgo-cadvisor
        restart: unless-stopped
        privileged: true # 这是关键，cAdvisor需要特权模式访问容器数据
        devices:
            - /dev/kmsg:/dev/kmsg # 用于收集内核事件
        volumes:
            # 挂载宿主机目录，让cAdvisor能访问容器运行时和数据
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        ports:
            - "28081:8080" # Web UI端口，可选，主要用于调试
        networks:
            - pgo-net

    # --------------------------------------------------
    # 日志
    loki:
        container_name: pgo-loki
        image: grafana/loki:3.5.9
        restart: unless-stopped
        command: "-config.file=/etc/loki/loki.yaml"
        ports:
            - 23100:3100
        networks:
            - pgo-net
        volumes:
            - ./config/loki.yaml:/etc/loki/loki.yaml
            - ./loki/data:/data/loki

    promtail:
        container_name: pgo-promtail
        image: grafana/promtail:3.5.9
        restart: unless-stopped
        command: -config.file=/etc/promtail/promtail.yaml
        networks:
            - pgo-net
        volumes:
            - ./backend/logs:/opt/app_logs:ro
            - ./config/promtail.yaml:/etc/promtail/promtail.yaml


networks:
    pgo-net:
