# 记录一些测试/调研的平台

name: pgo
services:
  rocky9:
    container_name: dr9
    image: dr9:latest
    restart: always
    command: /startup.sh
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 10022:22
      - 10000-10010:10000-10010
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./share:/root/share/
      - ./startup.sh:/startup.sh

      - ./profile:/etc/profile.d/pancake.sh
      - ./ssh_config:/etc/ssh/sshd_config.d/pancake.conf

      # 持久化 SSH 密钥（如果需要）
      # - ssh:/root/.ssh

networks:
    dev-net:
