#!/bin/bash
export LD_LIBRARY_PATH=/usr/lib:/usr/lib64:/usr/local/lib:/usr/local/lib64:${LD_LIBRARY_PATH}

# 常用别名
alias ll='ls -la'
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Image}}\t{{.Size}}"'
alias dp='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Image}}"'


export GOPATH=/root/go
export GOROOT=/usr/local/go
export PATH=/usr/local/go/bin:/root/go/bin:$PATH

. /root/.nvm/nvm.sh
