package main

import (
	"fmt"
	"log"
	"os"
)

// 生成 curd 的 dao 代码
const daoTplPath = "internal/abandonCodeService/data/dao_AbandonCode.go"

func genDaoCode(
	tblToSvrMap map[string]*Table,
	tplTable *Table,
) {
	daoTplBytes, err := os.ReadFile(daoTplPath)
	if err != nil {
		log.Fatalf("read tpl file failed, err: %v", err)
	}

	for _, tbl := range tblToSvrMap {

		daoTplCode := string(daoTplBytes)

		daoCodeStr := `// Code generated by tools/genCURD. DO NOT EDIT.` + "\n\n"

		daoCodeStr += codeReplace(daoTplCode, tplTable, tbl)

		daoOutputPath := fmt.Sprintf("./internal/%vService/data/", tbl.ServiceName)
		os.MkdirAll(daoOutputPath, 0755)
		err := os.WriteFile(daoOutputPath+"dao_"+tbl.UpperCamelName+".gen.go", []byte(daoCodeStr), 0644)
		if err != nil {
			log.Fatalf("write dao code failed, err: %v", err)
		}
	}
}
