package sheet2mysql

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/mozillazg/go-pinyin"
	"github.com/pancake-lee/pgo/pkg/papitable"
	"github.com/pancake-lee/pgo/pkg/putil"
)

type BuildDDLOptions struct {
	DatasheetID   string
	SourceComment string
}

type mysqlColumn struct {
	SourceName  string
	SourceType  papitable.FieldType
	Name        string
	Type        string
	Nullable    bool
	DefaultExpr string
	Comment     string
}

func BuildMysqlCreateTableSQL(tableNameRaw string,
	fieldList []*papitable.Field,
	options BuildDDLOptions,
) (sql string, warningList []string, err error) {
	if len(fieldList) == 0 {
		return "", nil, fmt.Errorf("field list is empty")
	}

	tableName, err := buildTableName(tableNameRaw)
	if err != nil {
		return "", nil, err
	}

	columnList, warningList, err := buildColumnList(fieldList, options)
	if err != nil {
		return "", warningList, err
	}
	if len(columnList) == 0 {
		return "", warningList, fmt.Errorf("no column can be generated from this sheet")
	}

	var sb strings.Builder

	sb.WriteString("DROP TABLE IF EXISTS `")
	sb.WriteString(tableName)
	sb.WriteString("`;\n\n")

	sb.WriteString("CREATE TABLE IF NOT EXISTS `")
	sb.WriteString(tableName)
	sb.WriteString("` (\n")
	sb.WriteString("  `id` INT NOT NULL AUTO_INCREMENT,\n")
	sb.WriteString("  `last_edit_from` varchar(200) NOT NULL DEFAULT \"\" COMMENT \"ltbl/mtbl, 避免循环触发同步逻辑\",\n\n")

	for _, c := range columnList {
		sb.WriteString("  `")
		sb.WriteString(c.Name)
		sb.WriteString("` ")
		sb.WriteString(c.Type)
		if c.Nullable {
			sb.WriteString(" NULL")
		} else {
			sb.WriteString(" NOT NULL")
		}
		if c.DefaultExpr != "" {
			sb.WriteString(" DEFAULT ")
			sb.WriteString(c.DefaultExpr)
		}
		sb.WriteString(" COMMENT '")
		sb.WriteString(escapeSQLComment(c.Comment))
		sb.WriteString("',\n")
	}

	sb.WriteString("  PRIMARY KEY (`id`)\n")

	sourceComment := escapeSQLComment(options.SourceComment)
	if sourceComment == "" {
		sourceComment = "generated by pgo sheet2mysql"
	}

	sb.WriteString(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='")
	sb.WriteString(sourceComment)
	sb.WriteString("';\n")

	if options.DatasheetID != "" {
		sb.WriteString("\n")
		sb.WriteString("-- source datasheetId: ")
		sb.WriteString(options.DatasheetID)
		sb.WriteString("\n")
	}

	return sb.String(), warningList, nil
}

func buildColumnList(fieldList []*papitable.Field,
	options BuildDDLOptions,
) (columnList []*mysqlColumn, warningList []string, err error) {
	colNameFromSourceMap := make(map[string]string)

	for i, field := range fieldList {
		if field == nil {
			warningList = append(warningList, fmt.Sprintf("第 %d 列为空，已跳过", i+1))
			continue
		}

		if isComputedField(field.Type) {
			continue // 计算列（公式/引用/按钮）不生成 MySQL 字段
		}

		colName, convErr := displayNameToIdentifier(field.Name, fmt.Sprintf("col_%02d", i+1), true)
		if convErr != nil {
			return columnList, warningList, fmt.Errorf("字段[%s] 名称转换失败: %w", field.Name, convErr)
		}

		if oldSource, exists := colNameFromSourceMap[colName]; exists {
			return columnList, warningList,
				fmt.Errorf("字段名转换后冲突: [%s] 和 [%s] 均映射为 [%s]，请在 APITable 修改字段名后再生成", oldSource, field.Name, colName)
		}
		colNameFromSourceMap[colName] = field.Name

		colType, warning := mapFieldToMysqlType(field)
		if warning != "" {
			warningList = append(warningList, warning)
		}

		nullable, defaultExpr := inferColumnNullAndDefault(colType)

		columnList = append(columnList, &mysqlColumn{
			SourceName:  field.Name,
			SourceType:  field.Type,
			Name:        colName,
			Type:        colType,
			Nullable:    nullable,
			DefaultExpr: defaultExpr,
			Comment:     fmt.Sprintf("source[%s/%s]", field.Name, field.Type),
		})
	}

	return columnList, warningList, nil
}

func mapFieldToMysqlType(field *papitable.Field) (mysqlType string, warning string) {
	switch field.Type {
	case papitable.FIELD_TYPE_TEXT:
		return "varchar(255)", ""
	case papitable.FIELD_TYPE_SINGLE_SELECT:
		return "varchar(191)", ""
	case papitable.FIELD_TYPE_MULTI_SELECT:
		return "json", ""
	case papitable.FIELD_TYPE_NUMBER:
		scale := readPrecision(field.Property, 0)
		return decimalType(scale), ""
	case papitable.FIELD_TYPE_CURRENCY:
		scale := readPrecision(field.Property, 2)
		return decimalType(scale), ""
	case papitable.FIELD_TYPE_PERCENT:
		scale := readPrecision(field.Property, 2)
		return decimalType(scale), ""
	case papitable.FIELD_TYPE_DATE_TIME,
		papitable.FIELD_TYPE_CREATED_TIME,
		papitable.FIELD_TYPE_LAST_MODIFIED_TIME:
		return "datetime(3)", ""
	case papitable.FIELD_TYPE_ATTACHMENT,
		papitable.FIELD_TYPE_MEMBER,
		papitable.FIELD_TYPE_ONE_WAY_LINK,
		papitable.FIELD_TYPE_TWO_WAY_LINK,
		papitable.FIELD_TYPE_MAGIC_LOOKUP,
		papitable.FIELD_TYPE_CREATED_BY,
		papitable.FIELD_TYPE_LAST_MODIFIED_BY:
		return "json", ""
	case papitable.FIELD_TYPE_CHECKBOX:
		return "tinyint(1)", ""
	case papitable.FIELD_TYPE_RATING:
		return "int", ""
	case papitable.FIELD_TYPE_URL:
		return "varchar(1024)", ""
	case papitable.FIELD_TYPE_PHONE:
		return "varchar(64)", ""
	case papitable.FIELD_TYPE_EMAIL:
		return "varchar(255)", ""
	case papitable.FIELD_TYPE_WORK_DOC:
		return "text", ""
	case papitable.FIELD_TYPE_FORMULA:
		return "text", ""
	case papitable.FIELD_TYPE_AUTO_NUMBER:
		return "bigint", ""
	case papitable.FIELD_TYPE_BUTTON:
		return "varchar(191)", ""
	default:
		warning = fmt.Sprintf("字段[%s] 类型[%s]暂无精确映射，降级为 text", field.Name, field.Type)
		return "text", warning
	}
}

func readPrecision(property map[string]any, defaultVal int32) int32 {
	if property == nil {
		return defaultVal
	}

	precision, ok := property["precision"]
	if !ok {
		return defaultVal
	}

	scale := putil.AnyToInt32(precision, defaultVal)
	if scale < 0 {
		return defaultVal
	}
	if scale > 8 {
		return 8
	}
	return scale
}

func decimalType(scale int32) string {
	if scale <= 0 {
		return "decimal(20,0)"
	}
	return fmt.Sprintf("decimal(20,%d)", scale)
}

func isComputedField(fieldType papitable.FieldType) bool {
	switch fieldType {
	case papitable.FIELD_TYPE_FORMULA,
		papitable.FIELD_TYPE_MAGIC_LOOKUP,
		papitable.FIELD_TYPE_BUTTON:
		return true
	default:
		return false
	}
}

func sanitizeIdentifier(raw string, fallback string, preserveCase bool) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return fallback
	}

	var sb strings.Builder
	lastIsUnderline := false

	for _, r := range raw {
		if r >= 'A' && r <= 'Z' {
			if !preserveCase {
				r = unicode.ToLower(r)
			}
			sb.WriteRune(r)
			lastIsUnderline = false
			continue
		}
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			sb.WriteRune(r)
			lastIsUnderline = false
			continue
		}

		if !lastIsUnderline {
			sb.WriteRune('_')
			lastIsUnderline = true
		}
	}

	val := strings.Trim(sb.String(), "_")
	if val == "" {
		val = fallback
	}

	if len(val) > 60 {
		val = val[:60]
	}

	if val[0] >= '0' && val[0] <= '9' {
		val = "c_" + val
	}

	return val
}

func buildTableName(tableNameRaw string) (string, error) {
	base, err := displayNameToIdentifier(tableNameRaw, "sheet_table", true)
	if err != nil {
		return "", fmt.Errorf("table name convert failed: %w", err)
	}

	if !strings.HasPrefix(strings.ToLower(base), "sheet_") {
		base = "sheet_" + base
	}

	return base, nil
}

func displayNameToIdentifier(raw string, fallback string, preserveCase bool) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", fmt.Errorf("display name is empty")
	}

	converted, err := convertChineseToPinyin(raw)
	if err != nil {
		return "", err
	}

	name := sanitizeIdentifier(converted, fallback, preserveCase)
	if name == "" {
		return "", fmt.Errorf("identifier is empty after sanitize")
	}

	return name, nil
}

func convertChineseToPinyin(raw string) (string, error) {
	args := pinyin.NewArgs()
	args.Style = pinyin.Normal

	var sb strings.Builder
	lastIsUnderline := false

	for _, r := range raw {
		switch {
		case unicode.Is(unicode.Han, r):
			py := pinyin.SinglePinyin(r, args)
			if len(py) == 0 || py[0] == "" {
				return "", fmt.Errorf("无法转换汉字[%c]为拼音", r)
			}
			sb.WriteString(strings.ToLower(py[0]))
			lastIsUnderline = false
		case (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9'):
			sb.WriteRune(r)
			lastIsUnderline = false
		case r == '_':
			sb.WriteRune(r)
			lastIsUnderline = true
		default:
			if !lastIsUnderline {
				sb.WriteRune('_')
				lastIsUnderline = true
			}
		}
	}

	return sb.String(), nil
}

func inferColumnNullAndDefault(colType string) (nullable bool, defaultExpr string) {
	lower := strings.ToLower(colType)
	if strings.HasPrefix(lower, "varchar") || lower == "text" {
		return false, "\"\""
	}
	return true, ""
}

func escapeSQLComment(comment string) string {
	return strings.ReplaceAll(comment, "'", "''")
}
