apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://pgo-prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
  - name: loki
    type: loki
    access: proxy
    url: http://pgo-loki:3100
  - name: pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    access: proxy
    url: http://pgo-pyroscope:4040
    jsonData:
      minStep: 15s
