# wget https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64
# chmod +x docker-compose-linux-x86_64 
# ln -s /home/gogogo/docker/docker-compose-linux-x86_64 /usr/local/bin/docker-compose

version: "3"

services:
  postgres:
    container_name: go-pg
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gogogo
      POSTGRES_PASSWORD: gogogo
    networks:
      - go-net
    volumes:
      - /home/gogogo/docker/data/postgresql/data:/var/lib/postgresql/data

networks:
  go-net:

