// Code generated by tools/genCURD. DO NOT EDIT.

package genCURD

import (
	"fmt"
	"os"
	"strings"

	"github.com/pancake-lee/pgo/pkg/plogger"
	"github.com/pancake-lee/pgo/pkg/putil"
)

// 生成服务的 main 文件
const mainTplPath = "internal/abandonCodeService/abandonService.go"

// 遍历每个service，生成对应的main文件
func genMainCode(
	tblMap map[string]*Table,
	tplTable *Table,
) error {
	mainTplBytes, err := os.ReadFile(mainTplPath)
	if err != nil {
		return fmt.Errorf("read tpl file failed: %w", err)
	}

	// 收集所有的服务名
	svcNameMap := make(map[string]bool)
	for _, tbl := range tblMap {
		svcNameMap[tbl.ServiceName] = true
	}

	for svcName := range svcNameMap {
		plogger.Debugf("gen main code for service[%v]", svcName)

		mainTplCode := string(mainTplBytes)
		mainCodeStr := mainReplace(mainTplCode, tplTable, svcName)

		mainOutputPath := fmt.Sprintf("./internal/%vService/", svcName)
		_ = os.MkdirAll(mainOutputPath, 0755)

		// 生成的main文件名取决于原始业务单元名, 对于abandonCodeService保持原名
		// 而其他服务也使用"<serviceName>Service.go"的模式命名
		mainFileName := svcName + "Service.go"
		mainFilePath := mainOutputPath + mainFileName
		if _, statErr := os.Stat(mainFilePath); statErr == nil {
			plogger.Debugf("main file exists, skip generate: %v", mainFilePath)
			continue
		} else if !os.IsNotExist(statErr) {
			return fmt.Errorf("check main file failed: %w", statErr)
		}

		err = os.WriteFile(mainFilePath, []byte(mainCodeStr), 0644)
		if err != nil {
			return fmt.Errorf("write main code failed: %w", err)
		}
	}

	return nil
}

// 替换表名相关代码，dao/pb/service都会用到
func mainReplace(codeStr string, tplTable *Table, svcName string) string {
	codeStr = strings.ReplaceAll(codeStr,
		tplTable.ServiceName, svcName)
	codeStr = strings.ReplaceAll(codeStr,
		putil.StrToUpperCamelCase(tplTable.ServiceName),
		putil.StrToUpperCamelCase(svcName))
	codeStr = strings.ReplaceAll(codeStr,
		putil.StrToLowerCamelCase(tplTable.ServiceName),
		putil.StrToLowerCamelCase(svcName))

	return codeStr
}
