package genCURD

import (
	"fmt"
	"os"
	"strings"

	"github.com/pancake-lee/pgo/pkg/plogger"
	"github.com/pancake-lee/pgo/pkg/putil"
)

// 生成 curd 的 service 代码，包括 DO 和 DTO 的转换代码，基础 curd 的实现
const svcTplPath = "internal/abandonCodeService/service/svc_AbandonCode.go"
const svrTplPath = "internal/abandonCodeService/service/svr_AbandonCode.go"

// 遍历每个表，以表为单位，生成一个接口实现代码文件
// 以service为单位，生成一个svr代码文件，实现grpc相关定义代码
func genServiceCode(
	tblMap map[string]*Table,
	tplTable *Table,
) error {
	svcNameToTblMap := make(map[string][]*Table)
	for _, tbl := range tblMap {
		svcNameToTblMap[tbl.ServiceName] = append(svcNameToTblMap[tbl.ServiceName], tbl)
	}

	svrTplBytes, err := os.ReadFile(svrTplPath)
	if err != nil {
		return fmt.Errorf("read tpl file failed: %w", err)
	}
	svrTpl := string(svrTplBytes)
	for svcName := range svcNameToTblMap {
		svrOutputPath := fmt.Sprintf("./internal/%vService/service/", svcName)
		_ = os.MkdirAll(svrOutputPath, 0755)

		err = genServerCode(svrTpl, tplTable.ServiceName,
			svcName, svrOutputPath+"z_svr_"+svcName+".gen.go")
		if err != nil {
			return err
		}
	}

	ctlTplBytes, err := os.ReadFile(svcTplPath)
	if err != nil {
		return fmt.Errorf("read tpl file failed: %w", err)
	}
	ctlTpl := string(ctlTplBytes)

	for svcName, tblList := range svcNameToTblMap {
		ctlOutputPath := fmt.Sprintf("./internal/%vService/service/", svcName)
		_ = os.MkdirAll(ctlOutputPath, 0755)
		for _, tbl := range tblList {
			err = genServiceCodeForOneTable(ctlTpl, tplTable, tbl, ctlOutputPath)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// --------------------------------------------------
// grpc定义代码，svr文件
func genServerCode(
	svrTpl string,
	tplSvcName, dstSvcName string,
	svrOutputPath string,
) error {
	plogger.Debugf("gen svr code for svr[%v]", dstSvcName)

	svcCodeStr := `// Code generated by tools/genCURD. DO NOT EDIT.` + "\n\n"
	svcCodeStr += svcNameReplace(svrTpl, tplSvcName, dstSvcName)

	err := os.WriteFile(svrOutputPath, []byte(svcCodeStr), 0644)
	if err != nil {
		return fmt.Errorf("write dao code failed: %w", err)
	}
	return nil
}

func svcNameReplace(codeStr, tplSvcName, dstSvcName string) string {
	codeStr = strings.ReplaceAll(codeStr,
		putil.StrToCamelCase(tplSvcName)+"CURDServer",
		putil.StrToCamelCase(dstSvcName)+"CURDServer")

	codeStr = strings.ReplaceAll(codeStr,
		putil.StrToCamelCase(tplSvcName)+"CURDHTTPServer",
		putil.StrToCamelCase(dstSvcName)+"CURDHTTPServer")

	codeStr = strings.ReplaceAll(codeStr,
		tplSvcName+"Service",
		dstSvcName+"Service")

	return codeStr
}

// --------------------------------------------------
func genServiceCodeForOneTable(
	ctlTpl string,
	tplTable *Table,
	tbl *Table,
	ctlOutputPath string,
) error {
	plogger.Debugf("gen svr code for tbl[%v]", tbl.TblName)

	svcCodeStr := `// Code generated by tools/genCURD. DO NOT EDIT.` + "\n\n"
	svcCodeStr += svcReplace(ctlTpl, tplTable, tbl)

	var importPkgList []string

	do2dtoCode := ""
	dto2doCode := ""
	for _, c := range tbl.ColList {
		if strings.EqualFold(c.originCol.DatabaseTypeName(), "date") ||
			strings.EqualFold(c.originCol.DatabaseTypeName(), "datetime") {
			do2dtoCode += fmt.Sprintf(
				"        %v: do.%v.Unix(),\n",
				c.apiFieldName, c.ormFieldName)
			dto2doCode += fmt.Sprintf(
				"        %v: time.Unix(dto.%v, 0),\n",
				c.ormFieldName, c.apiFieldName)
			importPkgList = append(importPkgList, "time")

		} else if strings.EqualFold(c.originCol.DatabaseTypeName(), "DECIMAL") {
			do2dtoCode += fmt.Sprintf(
				"        %v: putil.DecimalToStr(do.%v),\n",
				c.apiFieldName, c.ormFieldName)
			dto2doCode += fmt.Sprintf(
				"        %v: putil.StrToDecimal(dto.%v),\n",
				c.ormFieldName, c.apiFieldName)
			importPkgList = append(importPkgList, "github.com/pancake-lee/pgo/pkg/putil")

		} else {
			do2dtoCode += fmt.Sprintf(
				"        %v: do.%v,\n",
				c.apiFieldName, c.ormFieldName)
			dto2doCode += fmt.Sprintf(
				"        %v: dto.%v,\n",
				c.ormFieldName, c.apiFieldName)
		}
	}

	svcCodeStr = markPairTool.ReplaceAll("MARK REPLACE DO2DTO", svcCodeStr, do2dtoCode)
	svcCodeStr = markPairTool.ReplaceAll("MARK REPLACE DTO2DO", svcCodeStr, dto2doCode)

	importPkgList = putil.StrListUnique(importPkgList)
	importCode := ""
	for _, pkg := range importPkgList {
		importCode += fmt.Sprintf("import \"%v\"\n", pkg)
	}
	svcCodeStr = markPairTool.ReplaceAll("MARK REPLACE IMPORT", svcCodeStr, importCode)

	err := os.WriteFile(ctlOutputPath+"z_svc_"+tbl.LowerCamelName+".gen.go", []byte(svcCodeStr), 0644)
	if err != nil {
		return fmt.Errorf("write dao code failed: %w", err)
	}
	return nil
}

func svcReplace(
	codeStr string,
	tplTable *Table,
	tbl *Table,
) string {
	if tbl.PriCol == nil {
		codeStr = markPairTool.ReplaceAll("MARK REMOVE IF NO PRIMARY KEY", codeStr, "")
	} else {
		codeStr = markPairTool.RemoveMarkSelf("MARK REMOVE IF NO PRIMARY KEY", codeStr)
		codeStr = tblPriIdxReplace(codeStr, tplTable, tbl)
		codeStr = tblIdxReplaceService(codeStr, tplTable, tbl)
	}

	codeStr = svcNameReplace(codeStr,
		tplTable.ServiceName, tbl.ServiceName)

	return tblNameReplace(codeStr, tplTable, tbl)
}

func tblIdxReplaceService(codeStr string, tplTable *Table, tbl *Table) string {
	indexColPass := ""
	for _, idx := range tbl.IdxList {
		for _, f := range idx.Fields {
			indexColPass += fmt.Sprintf("            req.%vList,\n",
				f.apiFieldName)
		}
	}
	codeStr = markPairTool.ReplaceAll(
		"MARK REPLACE IDX COL", codeStr, indexColPass)

	return codeStr
}
