// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"github.com/pancake-lee/pgo/internal/pkg/db"
	"github.com/pancake-lee/pgo/internal/pkg/db/model"
	"github.com/pancake-lee/pgo/internal/pkg/perr"
	"github.com/pancake-lee/pgo/pkg/papp"
)

type SheetCeshibiaoDO = model.SheetCeshibiao

type sheetCeshibiaoDAO struct{}

var SheetCeshibiaoDAO sheetCeshibiaoDAO

func (*sheetCeshibiaoDAO) Add(ctx *papp.AppCtx, sheetCeshibiao *SheetCeshibiaoDO) error {
	if sheetCeshibiao == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().SheetCeshibiao
	err := q.WithContext(ctx).Create(sheetCeshibiao)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*sheetCeshibiaoDAO) GetAll(ctx *papp.AppCtx,
) (sheetCeshibiaoList []*SheetCeshibiaoDO, err error) {
	q := db.GetQuery().SheetCeshibiao
	sheetCeshibiaoList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return sheetCeshibiaoList, nil
}

func (*sheetCeshibiaoDAO) GetByIndex(ctx *papp.AppCtx,
IDList []int32,
) ([]*SheetCeshibiaoDO, error) {
	q := db.GetQuery().SheetCeshibiao
	do := q.WithContext(ctx)

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*sheetCeshibiaoDAO) UpdateByID(ctx *papp.AppCtx, do *SheetCeshibiaoDO) error {
	if do.ID == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().SheetCeshibiao
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*sheetCeshibiaoDAO) DelByID(ctx *papp.AppCtx, idx1 int32) error {
	if idx1 == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().SheetCeshibiao
	_, err := q.WithContext(ctx).Where(q.ID.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*sheetCeshibiaoDAO) DelByIDList(ctx *papp.AppCtx, idx1List []int32) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().SheetCeshibiao
	_, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*sheetCeshibiaoDAO) GetByID(ctx *papp.AppCtx, idx1 int32,
) (sheetCeshibiao *SheetCeshibiaoDO, err error) {
	if idx1 == 0 {
		return sheetCeshibiao, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().SheetCeshibiao
	sheetCeshibiao, err = q.WithContext(ctx).
		Where(q.ID.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return sheetCeshibiao, nil
}

func (*sheetCeshibiaoDAO) GetByIDList(ctx *papp.AppCtx, idx1List []int32,
) (sheetCeshibiaoMap map[int32]*SheetCeshibiaoDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().SheetCeshibiao
	l, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	sheetCeshibiaoMap = make(map[int32]*SheetCeshibiaoDO)
	for _, i := range l {
		sheetCeshibiaoMap[i.ID] = i
	}
	return sheetCeshibiaoMap, nil
}

