// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTask = "task"

// Task mapped from table <task>
type Task struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID   int32     `gorm:"column:parent_id;not null" json:"parent_id"`
	PrevID     int32     `gorm:"column:prev_id;not null" json:"prev_id"`
	Task       string    `gorm:"column:task;not null" json:"task"`
	Status     int32     `gorm:"column:status;not null" json:"status"`
	Estimate   int32     `gorm:"column:estimate;not null" json:"estimate"`
	Start      time.Time `gorm:"column:start;default:CURRENT_TIMESTAMP" json:"start"`
	End        time.Time `gorm:"column:end;default:CURRENT_TIMESTAMP" json:"end"`
	Desc       string    `gorm:"column:desc;not null" json:"desc"`
	Metadata   string    `gorm:"column:metadata;not null" json:"metadata"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
