// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID int32 `gorm:"column:id;primaryKey;autoIncrement:true;comment:The primary key of the table" json:"id"` // The primary key of the table
	/*
		The name of
		 the user
	*/
	UserName string `gorm:"column:user_name;not null;comment:The name of\n the user" json:"user_name"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
