// Code generated by tools/genCURD. DO NOT EDIT.

package service


import (
	"context"

	"github.com/pancake-lee/pgo/internal/pkg/api"
	"github.com/pancake-lee/pgo/internal/defaultService/data"
	"github.com/pancake-lee/pgo/pkg/papp"
)

func DO2DTO_SheetCeshibiao(do *data.SheetCeshibiaoDO) *api.SheetCeshibiaoInfo {
	if do == nil {
		return nil
	}
	return &api.SheetCeshibiaoInfo{
        ID: do.ID,
        LastEditFrom: do.LastEditFrom,
        Jingtou: do.Jingtou,
        Changci: do.Changci,
        Zhuangtai: do.Zhuangtai,
	}
}
func DTO2DO_SheetCeshibiao(dto *api.SheetCeshibiaoInfo) *data.SheetCeshibiaoDO {
	if dto == nil {
		return nil
	}
	return &data.SheetCeshibiaoDO{
        ID: dto.ID,
        LastEditFrom: dto.LastEditFrom,
        Jingtou: dto.Jingtou,
        Changci: dto.Changci,
        Zhuangtai: dto.Zhuangtai,
	}
}

func (s *DefaultCURDServer) AddSheetCeshibiao(
	_ctx context.Context, req *api.AddSheetCeshibiaoRequest,
) (resp *api.AddSheetCeshibiaoResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.SheetCeshibiao == nil {
		return nil, api.ErrorInvalidArgument("")
	}
	newData := DTO2DO_SheetCeshibiao(req.SheetCeshibiao)

	err = data.SheetCeshibiaoDAO.Add(ctx, newData)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}

	ctx.Log.Debugf("AddSheetCeshibiao: %v", newData.ID)

	resp = new(api.AddSheetCeshibiaoResponse)
	resp.SheetCeshibiao = DO2DTO_SheetCeshibiao(newData)
	return resp, nil
}

func (s *DefaultCURDServer) GetSheetCeshibiaoList(
	_ctx context.Context, req *api.GetSheetCeshibiaoListRequest,
) (resp *api.GetSheetCeshibiaoListResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	var dataList []*data.SheetCeshibiaoDO

	if len(req.IDList) != 0 {
		ctx.Log.Debugf("GetSheetCeshibiaoList: %v", req.IDList)

		dataList, err = data.SheetCeshibiaoDAO.GetByIndex(ctx,
            req.IDList,
		)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}
	} else {

		dataList, err = data.SheetCeshibiaoDAO.GetAll(ctx)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}

	}

	ctx.Log.Debugf("GetSheetCeshibiaoList resp len %v", len(dataList))

	resp = new(api.GetSheetCeshibiaoListResponse)
	resp.SheetCeshibiaoList = make([]*api.SheetCeshibiaoInfo, 0, len(dataList))
	for _, data := range dataList {
		resp.SheetCeshibiaoList = append(resp.SheetCeshibiaoList, DO2DTO_SheetCeshibiao(data))
	}
	return resp, nil
}


func (s *DefaultCURDServer) UpdateSheetCeshibiao(
	_ctx context.Context, req *api.UpdateSheetCeshibiaoRequest,
) (resp *api.UpdateSheetCeshibiaoResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.SheetCeshibiao == nil {
		return nil, api.ErrorInvalidArgument("")
	}

	do := DTO2DO_SheetCeshibiao(req.SheetCeshibiao)
	err = data.SheetCeshibiaoDAO.UpdateByID(ctx, do)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("UpdateSheetCeshibiao %v", req.SheetCeshibiao.ID)

	resp = new(api.UpdateSheetCeshibiaoResponse)
	d, err := data.SheetCeshibiaoDAO.GetByID(ctx, req.SheetCeshibiao.ID)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	resp.SheetCeshibiao = DO2DTO_SheetCeshibiao(d)
	return resp, nil
}

func (s *DefaultCURDServer) DelSheetCeshibiaoByIDList(
	_ctx context.Context, req *api.DelSheetCeshibiaoByIDListRequest,
) (resp *api.Empty, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if len(req.IDList) == 0 {
		return nil, nil
	}
	err = data.SheetCeshibiaoDAO.DelByIDList(ctx, req.IDList)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("DelSheetCeshibiaoByIDList %v", req.IDList)
	return nil, nil
}

