/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// --------------------------------------------------  tbl : user_role_assoc
type ApiUserRoleAssocInfo struct {
	ID int32 `json:"ID,omitempty"`
	CreateTime string `json:"createTime,omitempty"`
	CreateUser int32 `json:"createUser,omitempty"`
	UserID int32 `json:"userID,omitempty"`
	RoleID int32 `json:"roleID,omitempty"`
}
