/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// MARK REMOVE IF NO PRIMARY KEY START
type ApiUpdateAbandonCodeRequest struct {
	AbandonCode *ApiAbandonCodeInfo `json:"abandonCode,omitempty"`
}
