/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// --------------------------------------------------  tbl : user_dept_assoc
type ApiUserDeptAssocInfo struct {
	UserID int32 `json:"userID,omitempty"`
	DeptID int32 `json:"deptID,omitempty"`
	JobID int32 `json:"jobID,omitempty"`
}
