// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v3.21.9
// source: abandonCode.proto

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAbandonCodeAddAbandonCode = "/api.AbandonCode/AddAbandonCode"
const OperationAbandonCodeDelAbandonCodeByIds = "/api.AbandonCode/DelAbandonCodeByIds"
const OperationAbandonCodeGetAbandonCodeList = "/api.AbandonCode/GetAbandonCodeList"

type AbandonCodeHTTPServer interface {
	AddAbandonCode(context.Context, *AddAbandonCodeRequest) (*AddAbandonCodeResponse, error)
	// DelAbandonCodeByIds MARK 5 START 替换内容，没有索引的表，以替换的形式删除
	DelAbandonCodeByIds(context.Context, *DelAbandonCodeByIdsRequest) (*Empty, error)
	GetAbandonCodeList(context.Context, *GetAbandonCodeListRequest) (*GetAbandonCodeListResponse, error)
}

func RegisterAbandonCodeHTTPServer(s *http.Server, srv AbandonCodeHTTPServer) {
	r := s.Route("/")
	r.POST("/abandon-code", _AbandonCode_AddAbandonCode0_HTTP_Handler(srv))
	r.GET("/abandon-code", _AbandonCode_GetAbandonCodeList0_HTTP_Handler(srv))
	r.DELETE("/abandon-code", _AbandonCode_DelAbandonCodeByIds0_HTTP_Handler(srv))
}

func _AbandonCode_AddAbandonCode0_HTTP_Handler(srv AbandonCodeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddAbandonCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAbandonCodeAddAbandonCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddAbandonCode(ctx, req.(*AddAbandonCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddAbandonCodeResponse)
		return ctx.Result(200, reply)
	}
}

func _AbandonCode_GetAbandonCodeList0_HTTP_Handler(srv AbandonCodeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAbandonCodeListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAbandonCodeGetAbandonCodeList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAbandonCodeList(ctx, req.(*GetAbandonCodeListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAbandonCodeListResponse)
		return ctx.Result(200, reply)
	}
}

func _AbandonCode_DelAbandonCodeByIds0_HTTP_Handler(srv AbandonCodeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DelAbandonCodeByIdsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAbandonCodeDelAbandonCodeByIds)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DelAbandonCodeByIds(ctx, req.(*DelAbandonCodeByIdsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Empty)
		return ctx.Result(200, reply)
	}
}

type AbandonCodeHTTPClient interface {
	AddAbandonCode(ctx context.Context, req *AddAbandonCodeRequest, opts ...http.CallOption) (rsp *AddAbandonCodeResponse, err error)
	DelAbandonCodeByIds(ctx context.Context, req *DelAbandonCodeByIdsRequest, opts ...http.CallOption) (rsp *Empty, err error)
	GetAbandonCodeList(ctx context.Context, req *GetAbandonCodeListRequest, opts ...http.CallOption) (rsp *GetAbandonCodeListResponse, err error)
}

type AbandonCodeHTTPClientImpl struct {
	cc *http.Client
}

func NewAbandonCodeHTTPClient(client *http.Client) AbandonCodeHTTPClient {
	return &AbandonCodeHTTPClientImpl{client}
}

func (c *AbandonCodeHTTPClientImpl) AddAbandonCode(ctx context.Context, in *AddAbandonCodeRequest, opts ...http.CallOption) (*AddAbandonCodeResponse, error) {
	var out AddAbandonCodeResponse
	pattern := "/abandon-code"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAbandonCodeAddAbandonCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AbandonCodeHTTPClientImpl) DelAbandonCodeByIds(ctx context.Context, in *DelAbandonCodeByIdsRequest, opts ...http.CallOption) (*Empty, error) {
	var out Empty
	pattern := "/abandon-code"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAbandonCodeDelAbandonCodeByIds))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AbandonCodeHTTPClientImpl) GetAbandonCodeList(ctx context.Context, in *GetAbandonCodeListRequest, opts ...http.CallOption) (*GetAbandonCodeListResponse, error) {
	var out GetAbandonCodeListResponse
	pattern := "/abandon-code"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAbandonCodeGetAbandonCodeList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
