// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package api

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknow(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Unknow.String() && e.Code == 500
}

func ErrorUnknow(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_Unknow.String(), fmt.Sprintf(format, args...))
}

// 请求参数错误
func IsInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_InvalidArgument.String() && e.Code == 400
}

// 请求参数错误
func ErrorInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_InvalidArgument.String(), fmt.Sprintf(format, args...))
}
