// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"context"
	"errors"
	"pgo/internal/pkg/db"
	"pgo/internal/pkg/db/model"
)

type UserDeptDO = model.UserDept

type userDeptDAO struct{}

var UserDeptDAO userDeptDAO

func (*userDeptDAO) Add(ctx context.Context, userDept *UserDeptDO) error {
	if userDept == nil {
		return errors.New("param is invalid")
	}
	q := db.GetPG().UserDept
	err := q.WithContext(ctx).Create(userDept)
	if err != nil {
		return err
	}
	return err
}

func (*userDeptDAO) GetAll(ctx context.Context,
) (userDeptList []*UserDeptDO, err error) {
	q := db.GetPG().UserDept
	userDeptList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, err
	}
	return userDeptList, nil
}

func (*userDeptDAO) UpdateByID(ctx context.Context, do *UserDeptDO) error {
	if do.ID == 0 {
		return errors.New("param is invalid")
	}
	q := db.GetPG().UserDept
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return err
	}
	return err
}

func (*userDeptDAO) DelByID(ctx context.Context, iD int32) error {
	if iD == 0 {
		return errors.New("param is invalid")
	}
	q := db.GetPG().UserDept
	_, err := q.WithContext(ctx).Where(q.ID.Eq(iD)).Delete()
	if err != nil {
		return err
	}
	return err
}

func (*userDeptDAO) DelByIDList(ctx context.Context, iDList []int32) error {
	if len(iDList) == 0 {
		return nil
	}
	q := db.GetPG().UserDept
	_, err := q.WithContext(ctx).
		Where(q.ID.In(iDList...)).Delete()
	if err != nil {
		return err
	}
	return err
}

func (*userDeptDAO) GetByID(ctx context.Context, iD int32,
) (userDept *UserDeptDO, err error) {
	if iD == 0 {
		return userDept, errors.New("param is invalid")
	}

	q := db.GetPG().UserDept
	userDept, err = q.WithContext(ctx).
		Where(q.ID.Eq(iD)).First()
	if err != nil {
		return nil, err
	}
	return userDept, nil
}

func (*userDeptDAO) GetByIDList(ctx context.Context, iDList []int32,
) (userDeptMap map[int32]*UserDeptDO, err error) {
	if len(iDList) == 0 {
		return nil, nil
	}

	q := db.GetPG().UserDept
	l, err := q.WithContext(ctx).
		Where(q.ID.In(iDList...)).Find()
	if err != nil {
		return nil, err
	}
	userDeptMap = make(map[int32]*UserDeptDO)
	for _, i := range l {
		userDeptMap[i.ID] = i
	}
	return userDeptMap, nil
}

