// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"context"
	"pgo/internal/pkg/db"
	"pgo/internal/pkg/db/model"
	"pgo/internal/pkg/perr"
	"pgo/pkg/logger"
)

type UserDeptAssocDO = model.UserDeptAssoc

type userDeptAssocDAO struct{}

var UserDeptAssocDAO userDeptAssocDAO

func (*userDeptAssocDAO) Add(ctx context.Context, userDeptAssoc *UserDeptAssocDO) error {
	if userDeptAssoc == nil {
		return logger.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetPG().UserDeptAssoc
	err := q.WithContext(ctx).Create(userDeptAssoc)
	if err != nil {
		return logger.LogErr(err)
	}
	return nil
}

func (*userDeptAssocDAO) GetAll(ctx context.Context,
) (userDeptAssocList []*UserDeptAssocDO, err error) {
	q := db.GetPG().UserDeptAssoc
	userDeptAssocList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, logger.LogErr(err)
	}
	return userDeptAssocList, nil
}

