// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"context"

	"github.com/pancake-lee/pgo/internal/pkg/db"
	"github.com/pancake-lee/pgo/internal/pkg/db/model"
	"github.com/pancake-lee/pgo/internal/pkg/perr"
	"github.com/pancake-lee/pgo/pkg/plogger"
)

type UserRolePermissionAssocDO = model.UserRolePermissionAssoc

type userRolePermissionAssocDAO struct{}

var UserRolePermissionAssocDAO userRolePermissionAssocDAO

func (*userRolePermissionAssocDAO) Add(ctx context.Context, userRolePermissionAssoc *UserRolePermissionAssocDO) error {
	if userRolePermissionAssoc == nil {
		return plogger.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetPG().UserRolePermissionAssoc
	err := q.WithContext(ctx).Create(userRolePermissionAssoc)
	if err != nil {
		return plogger.LogErr(err)
	}
	return nil
}

func (*userRolePermissionAssocDAO) GetAll(ctx context.Context,
) (userRolePermissionAssocList []*UserRolePermissionAssocDO, err error) {
	q := db.GetPG().UserRolePermissionAssoc
	userRolePermissionAssocList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	return userRolePermissionAssocList, nil
}

func (*userRolePermissionAssocDAO) GetByIndex(ctx context.Context,
IDList []int32,
) ([]*UserRolePermissionAssocDO, error) {
	q := db.GetPG().UserRolePermissionAssoc
	do := q.WithContext(ctx)

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	return list, nil
}

func (*userRolePermissionAssocDAO) UpdateByID(ctx context.Context, do *UserRolePermissionAssocDO) error {
	if do.ID == 0 {
		return plogger.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetPG().UserRolePermissionAssoc
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return plogger.LogErr(err)
	}
	return nil
}

func (*userRolePermissionAssocDAO) DelByID(ctx context.Context, iD int32) error {
	if iD == 0 {
		return plogger.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetPG().UserRolePermissionAssoc
	_, err := q.WithContext(ctx).Where(q.ID.Eq(iD)).Delete()
	if err != nil {
		return plogger.LogErr(err)
	}
	return nil
}

func (*userRolePermissionAssocDAO) DelByIDList(ctx context.Context, iDList []int32) error {
	if len(iDList) == 0 {
		return nil
	}
	q := db.GetPG().UserRolePermissionAssoc
	_, err := q.WithContext(ctx).
		Where(q.ID.In(iDList...)).Delete()
	if err != nil {
		return plogger.LogErr(err)
	}
	return nil
}

func (*userRolePermissionAssocDAO) GetByID(ctx context.Context, iD int32,
) (userRolePermissionAssoc *UserRolePermissionAssocDO, err error) {
	if iD == 0 {
		return userRolePermissionAssoc, plogger.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetPG().UserRolePermissionAssoc
	userRolePermissionAssoc, err = q.WithContext(ctx).
		Where(q.ID.Eq(iD)).First()
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	return userRolePermissionAssoc, nil
}

func (*userRolePermissionAssocDAO) GetByIDList(ctx context.Context, iDList []int32,
) (userRolePermissionAssocMap map[int32]*UserRolePermissionAssocDO, err error) {
	if len(iDList) == 0 {
		return nil, nil
	}

	q := db.GetPG().UserRolePermissionAssoc
	l, err := q.WithContext(ctx).
		Where(q.ID.In(iDList...)).Find()
	if err != nil {
		return nil, plogger.LogErr(err)
	}
	userRolePermissionAssocMap = make(map[int32]*UserRolePermissionAssocDO)
	for _, i := range l {
		userRolePermissionAssocMap[i.ID] = i
	}
	return userRolePermissionAssocMap, nil
}

