// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"github.com/pancake-lee/pgo/internal/pkg/db"
	"github.com/pancake-lee/pgo/internal/pkg/db/model"
	"github.com/pancake-lee/pgo/internal/pkg/perr"
	"github.com/pancake-lee/pgo/pkg/papp"
)

type ProjectDO = model.Project

type projectDAO struct{}

var ProjectDAO projectDAO

func (*projectDAO) Add(ctx *papp.AppCtx, project *ProjectDO) error {
	if project == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().Project
	err := q.WithContext(ctx).Create(project)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*projectDAO) GetAll(ctx *papp.AppCtx,
) (projectList []*ProjectDO, err error) {
	q := db.GetQuery().Project
	projectList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return projectList, nil
}

func (*projectDAO) GetByIndex(ctx *papp.AppCtx,
projNameList []string,
IDList []int32,
) ([]*ProjectDO, error) {
	q := db.GetQuery().Project
	do := q.WithContext(ctx)

	if len(projNameList) > 0 {
		do = do.Where(q.ProjName.In(projNameList...))
	}

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*projectDAO) UpdateByID(ctx *papp.AppCtx, do *ProjectDO) error {
	if do.ID == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().Project
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*projectDAO) DelByID(ctx *papp.AppCtx, idx1 int32) error {
	if idx1 == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().Project
	_, err := q.WithContext(ctx).Where(q.ID.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*projectDAO) DelByIDList(ctx *papp.AppCtx, idx1List []int32) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().Project
	_, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*projectDAO) GetByID(ctx *papp.AppCtx, idx1 int32,
) (project *ProjectDO, err error) {
	if idx1 == 0 {
		return project, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().Project
	project, err = q.WithContext(ctx).
		Where(q.ID.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return project, nil
}

func (*projectDAO) GetByIDList(ctx *papp.AppCtx, idx1List []int32,
) (projectMap map[int32]*ProjectDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().Project
	l, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	projectMap = make(map[int32]*ProjectDO)
	for _, i := range l {
		projectMap[i.ID] = i
	}
	return projectMap, nil
}

