// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"github.com/pancake-lee/pgo/internal/pkg/db"
	"github.com/pancake-lee/pgo/internal/pkg/db/model"
	"github.com/pancake-lee/pgo/internal/pkg/perr"
	"github.com/pancake-lee/pgo/pkg/papp"
)

type UserDeptDO = model.UserDept

type userDeptDAO struct{}

var UserDeptDAO userDeptDAO

func (*userDeptDAO) Add(ctx *papp.AppCtx, userDept *UserDeptDO) error {
	if userDept == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().UserDept
	err := q.WithContext(ctx).Create(userDept)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userDeptDAO) GetAll(ctx *papp.AppCtx,
) (userDeptList []*UserDeptDO, err error) {
	q := db.GetQuery().UserDept
	userDeptList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return userDeptList, nil
}

func (*userDeptDAO) GetByIndex(ctx *papp.AppCtx,
deptPathList []string,
IDList []int32,
) ([]*UserDeptDO, error) {
	q := db.GetQuery().UserDept
	do := q.WithContext(ctx)

	if len(deptPathList) > 0 {
		do = do.Where(q.DeptPath.In(deptPathList...))
	}

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*userDeptDAO) UpdateByID(ctx *papp.AppCtx, do *UserDeptDO) error {
	if do.ID == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().UserDept
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userDeptDAO) DelByID(ctx *papp.AppCtx, idx1 int32) error {
	if idx1 == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().UserDept
	_, err := q.WithContext(ctx).Where(q.ID.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userDeptDAO) DelByIDList(ctx *papp.AppCtx, idx1List []int32) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().UserDept
	_, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userDeptDAO) GetByID(ctx *papp.AppCtx, idx1 int32,
) (userDept *UserDeptDO, err error) {
	if idx1 == 0 {
		return userDept, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().UserDept
	userDept, err = q.WithContext(ctx).
		Where(q.ID.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return userDept, nil
}

func (*userDeptDAO) GetByIDList(ctx *papp.AppCtx, idx1List []int32,
) (userDeptMap map[int32]*UserDeptDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().UserDept
	l, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	userDeptMap = make(map[int32]*UserDeptDO)
	for _, i := range l {
		userDeptMap[i.ID] = i
	}
	return userDeptMap, nil
}

