// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"github.com/pancake-lee/pgo/internal/pkg/db"
	"github.com/pancake-lee/pgo/internal/pkg/db/model"
	"github.com/pancake-lee/pgo/internal/pkg/perr"
	"github.com/pancake-lee/pgo/pkg/papp"
)

type UserRoleAssocDO = model.UserRoleAssoc

type userRoleAssocDAO struct{}

var UserRoleAssocDAO userRoleAssocDAO

func (*userRoleAssocDAO) Add(ctx *papp.AppCtx, userRoleAssoc *UserRoleAssocDO) error {
	if userRoleAssoc == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().UserRoleAssoc
	err := q.WithContext(ctx).Create(userRoleAssoc)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userRoleAssocDAO) GetAll(ctx *papp.AppCtx,
) (userRoleAssocList []*UserRoleAssocDO, err error) {
	q := db.GetQuery().UserRoleAssoc
	userRoleAssocList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return userRoleAssocList, nil
}

func (*userRoleAssocDAO) GetByIndex(ctx *papp.AppCtx,
userIDList []int32,
roleIDList []int32,
IDList []int32,
) ([]*UserRoleAssocDO, error) {
	q := db.GetQuery().UserRoleAssoc
	do := q.WithContext(ctx)

	if len(userIDList) > 0 {
		do = do.Where(q.UserID.In(userIDList...))
	}

	if len(roleIDList) > 0 {
		do = do.Where(q.RoleID.In(roleIDList...))
	}

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*userRoleAssocDAO) UpdateByID(ctx *papp.AppCtx, do *UserRoleAssocDO) error {
	if do.ID == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().UserRoleAssoc
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userRoleAssocDAO) DelByID(ctx *papp.AppCtx, idx1 int32) error {
	if idx1 == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().UserRoleAssoc
	_, err := q.WithContext(ctx).Where(q.ID.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userRoleAssocDAO) DelByIDList(ctx *papp.AppCtx, idx1List []int32) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().UserRoleAssoc
	_, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userRoleAssocDAO) GetByID(ctx *papp.AppCtx, idx1 int32,
) (userRoleAssoc *UserRoleAssocDO, err error) {
	if idx1 == 0 {
		return userRoleAssoc, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().UserRoleAssoc
	userRoleAssoc, err = q.WithContext(ctx).
		Where(q.ID.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return userRoleAssoc, nil
}

func (*userRoleAssocDAO) GetByIDList(ctx *papp.AppCtx, idx1List []int32,
) (userRoleAssocMap map[int32]*UserRoleAssocDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().UserRoleAssoc
	l, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	userRoleAssocMap = make(map[int32]*UserRoleAssocDO)
	for _, i := range l {
		userRoleAssocMap[i.ID] = i
	}
	return userRoleAssocMap, nil
}

