// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"github.com/pancake-lee/pgo/internal/pkg/db"
	"github.com/pancake-lee/pgo/internal/pkg/db/model"
	"github.com/pancake-lee/pgo/internal/pkg/perr"
	"github.com/pancake-lee/pgo/pkg/papp"
)

type UserRolePermissionAssocDO = model.UserRolePermissionAssoc

type userRolePermissionAssocDAO struct{}

var UserRolePermissionAssocDAO userRolePermissionAssocDAO

func (*userRolePermissionAssocDAO) Add(ctx *papp.AppCtx, userRolePermissionAssoc *UserRolePermissionAssocDO) error {
	if userRolePermissionAssoc == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().UserRolePermissionAssoc
	err := q.WithContext(ctx).Create(userRolePermissionAssoc)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userRolePermissionAssocDAO) GetAll(ctx *papp.AppCtx,
) (userRolePermissionAssocList []*UserRolePermissionAssocDO, err error) {
	q := db.GetQuery().UserRolePermissionAssoc
	userRolePermissionAssocList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return userRolePermissionAssocList, nil
}

func (*userRolePermissionAssocDAO) GetByIndex(ctx *papp.AppCtx,
IDList []int32,
) ([]*UserRolePermissionAssocDO, error) {
	q := db.GetQuery().UserRolePermissionAssoc
	do := q.WithContext(ctx)

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*userRolePermissionAssocDAO) UpdateByID(ctx *papp.AppCtx, do *UserRolePermissionAssocDO) error {
	if do.ID == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().UserRolePermissionAssoc
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userRolePermissionAssocDAO) DelByID(ctx *papp.AppCtx, idx1 int32) error {
	if idx1 == 0 {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().UserRolePermissionAssoc
	_, err := q.WithContext(ctx).Where(q.ID.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userRolePermissionAssocDAO) DelByIDList(ctx *papp.AppCtx, idx1List []int32) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().UserRolePermissionAssoc
	_, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*userRolePermissionAssocDAO) GetByID(ctx *papp.AppCtx, idx1 int32,
) (userRolePermissionAssoc *UserRolePermissionAssocDO, err error) {
	if idx1 == 0 {
		return userRolePermissionAssoc, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().UserRolePermissionAssoc
	userRolePermissionAssoc, err = q.WithContext(ctx).
		Where(q.ID.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return userRolePermissionAssoc, nil
}

func (*userRolePermissionAssocDAO) GetByIDList(ctx *papp.AppCtx, idx1List []int32,
) (userRolePermissionAssocMap map[int32]*UserRolePermissionAssocDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().UserRolePermissionAssoc
	l, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	userRolePermissionAssocMap = make(map[int32]*UserRolePermissionAssocDO)
	for _, i := range l {
		userRolePermissionAssocMap[i.ID] = i
	}
	return userRolePermissionAssocMap, nil
}

