package genCURD

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/pancake-lee/pgo/pkg/plogger"
)

// 生成 curd 的 proto 定义，包括数据结构和接口定义
const pbTplPath = "proto/abandonCode.proto"
const pbOutputPath = "./proto/"

// 遍历每个表，以service为单位，生成一个pb代码文件
func genProto(
	tblToSvrMap map[string]*Table,
	tplTable *Table,
) error {
	svcNameToTblMap := make(map[string][]*Table)
	for _, tbl := range tblToSvrMap {
		svcNameToTblMap[tbl.ServiceName] = append(svcNameToTblMap[tbl.ServiceName], tbl)
	}

	pbTplBytes, err := os.ReadFile(pbTplPath)
	if err != nil {
		return fmt.Errorf("read tpl file failed: %w", err)
	}
	pbTpl := string(pbTplBytes)

	apiTpl := markPairTool.GetContent(pbTpl, "MARK REPEAT API")
	msgTpl := markPairTool.GetContent(pbTpl, "MARK REPEAT MSG")

	for svcName, tblList := range svcNameToTblMap {
		err = genProtoForOneService(svcName, tblList, pbTpl, apiTpl, msgTpl, tplTable)
		if err != nil {
			return err
		}
	}
	return nil
}

func genProtoForOneService(
	svcName string,
	tblList []*Table,
	pbTpl, apiTpl, msgTpl string,
	tplTable *Table,
) error {
	apiCodeForAllTable := ""
	msgCodeForAllTable := ""

	sort.Slice(tblList, func(i, j int) bool {
		return tblList[i].TblName < tblList[j].TblName
	})

	for _, tbl := range tblList {
		plogger.Debugf("gen pb code for tbl[%v]", tbl.TblName)

		apiCode := pbReplace(apiTpl, tplTable, tbl)
		apiCodeForAllTable += apiCode

		msgCode := pbReplace(msgTpl, tplTable, tbl)

		pbColList := ""
		for i, c := range tbl.ColList {
			pbColList += fmt.Sprintf("    %v %v = %v;\n",
				c.pbFieldType, c.pbFieldName, i+1)
		}

		msgCode = markPairTool.ReplaceAll("MARK REPLACE PB COL",
			msgCode, pbColList)

		pbKeyColList := ""
		if tbl.PriCol != nil {
			pbKeyColList = fmt.Sprintf("    repeated %v %vList = 1;\n",
				tbl.PriCol.pbFieldType, tbl.PriCol.pbFieldName)
		}
		msgCode = markPairTool.ReplaceAll("MARK REPLACE PRIMARY IDX",
			msgCode, pbKeyColList)

		msgCodeForAllTable += msgCode
	}

	pbCodeStr := `// Code generated by tools/genCURD. DO NOT EDIT.` + "\n\n"
	pbCodeStr += pbTpl

	pbCodeStr = strings.ReplaceAll(pbCodeStr, tplTable.ServiceName, svcName)
	pbCodeStr = markPairTool.ReplaceAll("MARK REPEAT API", pbCodeStr, apiCodeForAllTable)
	pbCodeStr = markPairTool.ReplaceAll("MARK REPEAT MSG", pbCodeStr, msgCodeForAllTable)

	_ = os.MkdirAll(pbOutputPath, 0755)
	err := os.WriteFile(pbOutputPath+"z_"+svcName+"Service.gen.proto", []byte(pbCodeStr), 0644)
	if err != nil {
		return fmt.Errorf("write pb code failed: %w", err)
	}
	return nil
}

func pbReplace(
	tplCode string,
	tplTable *Table,
	tbl *Table,
) string {
	codeStr := tplCode

	if tbl.PriCol == nil {
		codeStr = markPairTool.ReplaceAll("MARK REMOVE IF NO PRIMARY KEY", codeStr, "")
	} else {
		codeStr = markPairTool.RemoveMarkSelf("MARK REMOVE IF NO PRIMARY KEY", codeStr)
		codeStr = tblPriIdxReplace(codeStr, tplTable, tbl)
		codeStr = tblIdxReplaceProto(codeStr, tplTable, tbl)
	}

	codeStr = tblNameReplace(codeStr, tplTable, tbl)
	return codeStr
}

func tblIdxReplaceProto(codeStr string, tplTable *Table, tbl *Table) string {
	indexColDef := ""
	i := 1
	for _, idx := range tbl.IdxList {
		for _, f := range idx.Fields {
			indexColDef += fmt.Sprintf("    repeated %v %vList = %v;\n",
				f.pbFieldType, f.pbFieldName, i)
			i++
		}
	}
	codeStr = markPairTool.ReplaceAll(
		"MARK REPLACE IDX COL", codeStr, indexColDef)

	return codeStr
}
