// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: userService.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_userService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_userService_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_userService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_userService_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EditUserNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserNameRequest) Reset() {
	*x = EditUserNameRequest{}
	mi := &file_userService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserNameRequest) ProtoMessage() {}

func (x *EditUserNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserNameRequest.ProtoReflect.Descriptor instead.
func (*EditUserNameRequest) Descriptor() ([]byte, []int) {
	return file_userService_proto_rawDescGZIP(), []int{2}
}

func (x *EditUserNameRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *EditUserNameRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type DelUserDeptAssocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DeptID        int32                  `protobuf:"varint,2,opt,name=deptID,proto3" json:"deptID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserDeptAssocRequest) Reset() {
	*x = DelUserDeptAssocRequest{}
	mi := &file_userService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserDeptAssocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserDeptAssocRequest) ProtoMessage() {}

func (x *DelUserDeptAssocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserDeptAssocRequest.ProtoReflect.Descriptor instead.
func (*DelUserDeptAssocRequest) Descriptor() ([]byte, []int) {
	return file_userService_proto_rawDescGZIP(), []int{3}
}

func (x *DelUserDeptAssocRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *DelUserDeptAssocRequest) GetDeptID() int32 {
	if x != nil {
		return x.DeptID
	}
	return 0
}

type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ProjectID     int32                  `protobuf:"varint,2,opt,name=projectID,proto3" json:"projectID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_userService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_userService_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserPermissionsRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetUserPermissionsRequest) GetProjectID() int32 {
	if x != nil {
		return x.ProjectID
	}
	return 0
}

type GetUserPermissionsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActionToPathPattern map[string]string      `protobuf:"bytes,1,rep,name=actionToPathPattern,proto3" json:"actionToPathPattern,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_userService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_userService_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserPermissionsResponse) GetActionToPathPattern() map[string]string {
	if x != nil {
		return x.ActionToPathPattern
	}
	return nil
}

var File_userService_proto protoreflect.FileDescriptor

const file_userService_proto_rawDesc = "" +
	"\n" +
	"\x11userService.proto\x12\x03api\x1a\fcommon.proto\x1a\x17z_userService.gen.proto\x1a\x1cgoogle/api/annotations.proto\"*\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\"H\n" +
	"\rLoginResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.api.UserInfoR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"A\n" +
	"\x13EditUserNameRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\"I\n" +
	"\x17DelUserDeptAssocRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x16\n" +
	"\x06deptID\x18\x02 \x01(\x05R\x06deptID\"Q\n" +
	"\x19GetUserPermissionsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tprojectID\x18\x02 \x01(\x05R\tprojectID\"\xd0\x01\n" +
	"\x1aGetUserPermissionsResponse\x12j\n" +
	"\x13actionToPathPattern\x18\x01 \x03(\v28.api.GetUserPermissionsResponse.ActionToPathPatternEntryR\x13actionToPathPattern\x1aF\n" +
	"\x18ActionToPathPatternEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe0\x02\n" +
	"\x04User\x12F\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/token\x12F\n" +
	"\fEditUserName\x12\x18.api.EditUserNameRequest\x1a\n" +
	".api.Empty\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*2\x05/user\x12V\n" +
	"\x10DelUserDeptAssoc\x12\x1c.api.DelUserDeptAssocRequest\x1a\n" +
	".api.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/user-dept-assoc\x12p\n" +
	"\x12GetUserPermissions\x12\x1e.api.GetUserPermissionsRequest\x1a\x1f.api.GetUserPermissionsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/user/permissionsB$Z\"github.com/pancake-lee/pgo/api;apib\x06proto3"

var (
	file_userService_proto_rawDescOnce sync.Once
	file_userService_proto_rawDescData []byte
)

func file_userService_proto_rawDescGZIP() []byte {
	file_userService_proto_rawDescOnce.Do(func() {
		file_userService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userService_proto_rawDesc), len(file_userService_proto_rawDesc)))
	})
	return file_userService_proto_rawDescData
}

var file_userService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_userService_proto_goTypes = []any{
	(*LoginRequest)(nil),               // 0: api.LoginRequest
	(*LoginResponse)(nil),              // 1: api.LoginResponse
	(*EditUserNameRequest)(nil),        // 2: api.EditUserNameRequest
	(*DelUserDeptAssocRequest)(nil),    // 3: api.DelUserDeptAssocRequest
	(*GetUserPermissionsRequest)(nil),  // 4: api.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil), // 5: api.GetUserPermissionsResponse
	nil,                                // 6: api.GetUserPermissionsResponse.ActionToPathPatternEntry
	(*UserInfo)(nil),                   // 7: api.UserInfo
	(*Empty)(nil),                      // 8: api.Empty
}
var file_userService_proto_depIdxs = []int32{
	7, // 0: api.LoginResponse.user:type_name -> api.UserInfo
	6, // 1: api.GetUserPermissionsResponse.actionToPathPattern:type_name -> api.GetUserPermissionsResponse.ActionToPathPatternEntry
	0, // 2: api.User.Login:input_type -> api.LoginRequest
	2, // 3: api.User.EditUserName:input_type -> api.EditUserNameRequest
	3, // 4: api.User.DelUserDeptAssoc:input_type -> api.DelUserDeptAssocRequest
	4, // 5: api.User.GetUserPermissions:input_type -> api.GetUserPermissionsRequest
	1, // 6: api.User.Login:output_type -> api.LoginResponse
	8, // 7: api.User.EditUserName:output_type -> api.Empty
	8, // 8: api.User.DelUserDeptAssoc:output_type -> api.Empty
	5, // 9: api.User.GetUserPermissions:output_type -> api.GetUserPermissionsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_userService_proto_init() }
func file_userService_proto_init() {
	if File_userService_proto != nil {
		return
	}
	file_common_proto_init()
	file_z_userService_gen_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userService_proto_rawDesc), len(file_userService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userService_proto_goTypes,
		DependencyIndexes: file_userService_proto_depIdxs,
		MessageInfos:      file_userService_proto_msgTypes,
	}.Build()
	File_userService_proto = out.File
	file_userService_proto_goTypes = nil
	file_userService_proto_depIdxs = nil
}
