// Code generated by tools/genCURD. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: z_userService.gen.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserCURD_AddProject_FullMethodName                         = "/api.userCURD/AddProject"
	UserCURD_GetProjectList_FullMethodName                     = "/api.userCURD/GetProjectList"
	UserCURD_UpdateProject_FullMethodName                      = "/api.userCURD/UpdateProject"
	UserCURD_DelProjectByIDList_FullMethodName                 = "/api.userCURD/DelProjectByIDList"
	UserCURD_GetProjectByProjName_FullMethodName               = "/api.userCURD/GetProjectByProjName"
	UserCURD_AddUser_FullMethodName                            = "/api.userCURD/AddUser"
	UserCURD_GetUserList_FullMethodName                        = "/api.userCURD/GetUserList"
	UserCURD_UpdateUser_FullMethodName                         = "/api.userCURD/UpdateUser"
	UserCURD_DelUserByIDList_FullMethodName                    = "/api.userCURD/DelUserByIDList"
	UserCURD_GetUserByUserName_FullMethodName                  = "/api.userCURD/GetUserByUserName"
	UserCURD_AddUserDept_FullMethodName                        = "/api.userCURD/AddUserDept"
	UserCURD_GetUserDeptList_FullMethodName                    = "/api.userCURD/GetUserDeptList"
	UserCURD_UpdateUserDept_FullMethodName                     = "/api.userCURD/UpdateUserDept"
	UserCURD_DelUserDeptByIDList_FullMethodName                = "/api.userCURD/DelUserDeptByIDList"
	UserCURD_GetUserDeptByDeptPath_FullMethodName              = "/api.userCURD/GetUserDeptByDeptPath"
	UserCURD_AddUserDeptAssoc_FullMethodName                   = "/api.userCURD/AddUserDeptAssoc"
	UserCURD_GetUserDeptAssocList_FullMethodName               = "/api.userCURD/GetUserDeptAssocList"
	UserCURD_UpdateUserDeptAssoc_FullMethodName                = "/api.userCURD/UpdateUserDeptAssoc"
	UserCURD_DelUserDeptAssocByIDList_FullMethodName           = "/api.userCURD/DelUserDeptAssocByIDList"
	UserCURD_GetUserDeptAssocByUserDept_FullMethodName         = "/api.userCURD/GetUserDeptAssocByUserDept"
	UserCURD_AddUserJob_FullMethodName                         = "/api.userCURD/AddUserJob"
	UserCURD_GetUserJobList_FullMethodName                     = "/api.userCURD/GetUserJobList"
	UserCURD_UpdateUserJob_FullMethodName                      = "/api.userCURD/UpdateUserJob"
	UserCURD_DelUserJobByIDList_FullMethodName                 = "/api.userCURD/DelUserJobByIDList"
	UserCURD_GetUserJobByJobName_FullMethodName                = "/api.userCURD/GetUserJobByJobName"
	UserCURD_AddUserProjectAssoc_FullMethodName                = "/api.userCURD/AddUserProjectAssoc"
	UserCURD_GetUserProjectAssocList_FullMethodName            = "/api.userCURD/GetUserProjectAssocList"
	UserCURD_UpdateUserProjectAssoc_FullMethodName             = "/api.userCURD/UpdateUserProjectAssoc"
	UserCURD_DelUserProjectAssocByIDList_FullMethodName        = "/api.userCURD/DelUserProjectAssocByIDList"
	UserCURD_GetUserProjectAssocByUserProj_FullMethodName      = "/api.userCURD/GetUserProjectAssocByUserProj"
	UserCURD_AddUserRole_FullMethodName                        = "/api.userCURD/AddUserRole"
	UserCURD_GetUserRoleList_FullMethodName                    = "/api.userCURD/GetUserRoleList"
	UserCURD_UpdateUserRole_FullMethodName                     = "/api.userCURD/UpdateUserRole"
	UserCURD_DelUserRoleByIDList_FullMethodName                = "/api.userCURD/DelUserRoleByIDList"
	UserCURD_AddUserRoleAssoc_FullMethodName                   = "/api.userCURD/AddUserRoleAssoc"
	UserCURD_GetUserRoleAssocList_FullMethodName               = "/api.userCURD/GetUserRoleAssocList"
	UserCURD_UpdateUserRoleAssoc_FullMethodName                = "/api.userCURD/UpdateUserRoleAssoc"
	UserCURD_DelUserRoleAssocByIDList_FullMethodName           = "/api.userCURD/DelUserRoleAssocByIDList"
	UserCURD_GetUserRoleAssocByUserRole_FullMethodName         = "/api.userCURD/GetUserRoleAssocByUserRole"
	UserCURD_AddUserRolePermissionAssoc_FullMethodName         = "/api.userCURD/AddUserRolePermissionAssoc"
	UserCURD_GetUserRolePermissionAssocList_FullMethodName     = "/api.userCURD/GetUserRolePermissionAssocList"
	UserCURD_UpdateUserRolePermissionAssoc_FullMethodName      = "/api.userCURD/UpdateUserRolePermissionAssoc"
	UserCURD_DelUserRolePermissionAssocByIDList_FullMethodName = "/api.userCURD/DelUserRolePermissionAssocByIDList"
)

// UserCURDClient is the client API for UserCURD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------------------------------
type UserCURDClient interface {
	// --------------------------------------------------
	// tbl : project
	AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*AddProjectResponse, error)
	GetProjectList(ctx context.Context, in *GetProjectListRequest, opts ...grpc.CallOption) (*GetProjectListResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error)
	DelProjectByIDList(ctx context.Context, in *DelProjectByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	GetProjectByProjName(ctx context.Context, in *GetProjectByProjNameRequest, opts ...grpc.CallOption) (*GetProjectByProjNameResponse, error)
	// --------------------------------------------------
	// tbl : user
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	GetUserList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DelUserByIDList(ctx context.Context, in *DelUserByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserByUserName(ctx context.Context, in *GetUserByUserNameRequest, opts ...grpc.CallOption) (*GetUserByUserNameResponse, error)
	// --------------------------------------------------
	// tbl : user_dept
	AddUserDept(ctx context.Context, in *AddUserDeptRequest, opts ...grpc.CallOption) (*AddUserDeptResponse, error)
	GetUserDeptList(ctx context.Context, in *GetUserDeptListRequest, opts ...grpc.CallOption) (*GetUserDeptListResponse, error)
	UpdateUserDept(ctx context.Context, in *UpdateUserDeptRequest, opts ...grpc.CallOption) (*UpdateUserDeptResponse, error)
	DelUserDeptByIDList(ctx context.Context, in *DelUserDeptByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserDeptByDeptPath(ctx context.Context, in *GetUserDeptByDeptPathRequest, opts ...grpc.CallOption) (*GetUserDeptByDeptPathResponse, error)
	// --------------------------------------------------
	// tbl : user_dept_assoc
	AddUserDeptAssoc(ctx context.Context, in *AddUserDeptAssocRequest, opts ...grpc.CallOption) (*AddUserDeptAssocResponse, error)
	GetUserDeptAssocList(ctx context.Context, in *GetUserDeptAssocListRequest, opts ...grpc.CallOption) (*GetUserDeptAssocListResponse, error)
	UpdateUserDeptAssoc(ctx context.Context, in *UpdateUserDeptAssocRequest, opts ...grpc.CallOption) (*UpdateUserDeptAssocResponse, error)
	DelUserDeptAssocByIDList(ctx context.Context, in *DelUserDeptAssocByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserDeptAssocByUserDept(ctx context.Context, in *GetUserDeptAssocByUserDeptRequest, opts ...grpc.CallOption) (*GetUserDeptAssocByUserDeptResponse, error)
	// --------------------------------------------------
	// tbl : user_job
	AddUserJob(ctx context.Context, in *AddUserJobRequest, opts ...grpc.CallOption) (*AddUserJobResponse, error)
	GetUserJobList(ctx context.Context, in *GetUserJobListRequest, opts ...grpc.CallOption) (*GetUserJobListResponse, error)
	UpdateUserJob(ctx context.Context, in *UpdateUserJobRequest, opts ...grpc.CallOption) (*UpdateUserJobResponse, error)
	DelUserJobByIDList(ctx context.Context, in *DelUserJobByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserJobByJobName(ctx context.Context, in *GetUserJobByJobNameRequest, opts ...grpc.CallOption) (*GetUserJobByJobNameResponse, error)
	// --------------------------------------------------
	// tbl : user_project_assoc
	AddUserProjectAssoc(ctx context.Context, in *AddUserProjectAssocRequest, opts ...grpc.CallOption) (*AddUserProjectAssocResponse, error)
	GetUserProjectAssocList(ctx context.Context, in *GetUserProjectAssocListRequest, opts ...grpc.CallOption) (*GetUserProjectAssocListResponse, error)
	UpdateUserProjectAssoc(ctx context.Context, in *UpdateUserProjectAssocRequest, opts ...grpc.CallOption) (*UpdateUserProjectAssocResponse, error)
	DelUserProjectAssocByIDList(ctx context.Context, in *DelUserProjectAssocByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserProjectAssocByUserProj(ctx context.Context, in *GetUserProjectAssocByUserProjRequest, opts ...grpc.CallOption) (*GetUserProjectAssocByUserProjResponse, error)
	// --------------------------------------------------
	// tbl : user_role
	AddUserRole(ctx context.Context, in *AddUserRoleRequest, opts ...grpc.CallOption) (*AddUserRoleResponse, error)
	GetUserRoleList(ctx context.Context, in *GetUserRoleListRequest, opts ...grpc.CallOption) (*GetUserRoleListResponse, error)
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*UpdateUserRoleResponse, error)
	DelUserRoleByIDList(ctx context.Context, in *DelUserRoleByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	// --------------------------------------------------
	// tbl : user_role_assoc
	AddUserRoleAssoc(ctx context.Context, in *AddUserRoleAssocRequest, opts ...grpc.CallOption) (*AddUserRoleAssocResponse, error)
	GetUserRoleAssocList(ctx context.Context, in *GetUserRoleAssocListRequest, opts ...grpc.CallOption) (*GetUserRoleAssocListResponse, error)
	UpdateUserRoleAssoc(ctx context.Context, in *UpdateUserRoleAssocRequest, opts ...grpc.CallOption) (*UpdateUserRoleAssocResponse, error)
	DelUserRoleAssocByIDList(ctx context.Context, in *DelUserRoleAssocByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserRoleAssocByUserRole(ctx context.Context, in *GetUserRoleAssocByUserRoleRequest, opts ...grpc.CallOption) (*GetUserRoleAssocByUserRoleResponse, error)
	// --------------------------------------------------
	// tbl : user_role_permission_assoc
	AddUserRolePermissionAssoc(ctx context.Context, in *AddUserRolePermissionAssocRequest, opts ...grpc.CallOption) (*AddUserRolePermissionAssocResponse, error)
	GetUserRolePermissionAssocList(ctx context.Context, in *GetUserRolePermissionAssocListRequest, opts ...grpc.CallOption) (*GetUserRolePermissionAssocListResponse, error)
	UpdateUserRolePermissionAssoc(ctx context.Context, in *UpdateUserRolePermissionAssocRequest, opts ...grpc.CallOption) (*UpdateUserRolePermissionAssocResponse, error)
	DelUserRolePermissionAssocByIDList(ctx context.Context, in *DelUserRolePermissionAssocByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
}

type userCURDClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCURDClient(cc grpc.ClientConnInterface) UserCURDClient {
	return &userCURDClient{cc}
}

func (c *userCURDClient) AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*AddProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProjectResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetProjectList(ctx context.Context, in *GetProjectListRequest, opts ...grpc.CallOption) (*GetProjectListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetProjectList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProjectResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelProjectByIDList(ctx context.Context, in *DelProjectByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelProjectByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetProjectByProjName(ctx context.Context, in *GetProjectByProjNameRequest, opts ...grpc.CallOption) (*GetProjectByProjNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectByProjNameResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetProjectByProjName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelUserByIDList(ctx context.Context, in *DelUserByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelUserByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserByUserName(ctx context.Context, in *GetUserByUserNameRequest, opts ...grpc.CallOption) (*GetUserByUserNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByUserNameResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserByUserName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) AddUserDept(ctx context.Context, in *AddUserDeptRequest, opts ...grpc.CallOption) (*AddUserDeptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserDeptResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddUserDept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserDeptList(ctx context.Context, in *GetUserDeptListRequest, opts ...grpc.CallOption) (*GetUserDeptListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDeptListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserDeptList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateUserDept(ctx context.Context, in *UpdateUserDeptRequest, opts ...grpc.CallOption) (*UpdateUserDeptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserDeptResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateUserDept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelUserDeptByIDList(ctx context.Context, in *DelUserDeptByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelUserDeptByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserDeptByDeptPath(ctx context.Context, in *GetUserDeptByDeptPathRequest, opts ...grpc.CallOption) (*GetUserDeptByDeptPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDeptByDeptPathResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserDeptByDeptPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) AddUserDeptAssoc(ctx context.Context, in *AddUserDeptAssocRequest, opts ...grpc.CallOption) (*AddUserDeptAssocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserDeptAssocResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddUserDeptAssoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserDeptAssocList(ctx context.Context, in *GetUserDeptAssocListRequest, opts ...grpc.CallOption) (*GetUserDeptAssocListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDeptAssocListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserDeptAssocList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateUserDeptAssoc(ctx context.Context, in *UpdateUserDeptAssocRequest, opts ...grpc.CallOption) (*UpdateUserDeptAssocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserDeptAssocResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateUserDeptAssoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelUserDeptAssocByIDList(ctx context.Context, in *DelUserDeptAssocByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelUserDeptAssocByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserDeptAssocByUserDept(ctx context.Context, in *GetUserDeptAssocByUserDeptRequest, opts ...grpc.CallOption) (*GetUserDeptAssocByUserDeptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDeptAssocByUserDeptResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserDeptAssocByUserDept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) AddUserJob(ctx context.Context, in *AddUserJobRequest, opts ...grpc.CallOption) (*AddUserJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserJobResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddUserJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserJobList(ctx context.Context, in *GetUserJobListRequest, opts ...grpc.CallOption) (*GetUserJobListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserJobListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserJobList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateUserJob(ctx context.Context, in *UpdateUserJobRequest, opts ...grpc.CallOption) (*UpdateUserJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserJobResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateUserJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelUserJobByIDList(ctx context.Context, in *DelUserJobByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelUserJobByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserJobByJobName(ctx context.Context, in *GetUserJobByJobNameRequest, opts ...grpc.CallOption) (*GetUserJobByJobNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserJobByJobNameResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserJobByJobName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) AddUserProjectAssoc(ctx context.Context, in *AddUserProjectAssocRequest, opts ...grpc.CallOption) (*AddUserProjectAssocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserProjectAssocResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddUserProjectAssoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserProjectAssocList(ctx context.Context, in *GetUserProjectAssocListRequest, opts ...grpc.CallOption) (*GetUserProjectAssocListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProjectAssocListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserProjectAssocList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateUserProjectAssoc(ctx context.Context, in *UpdateUserProjectAssocRequest, opts ...grpc.CallOption) (*UpdateUserProjectAssocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserProjectAssocResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateUserProjectAssoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelUserProjectAssocByIDList(ctx context.Context, in *DelUserProjectAssocByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelUserProjectAssocByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserProjectAssocByUserProj(ctx context.Context, in *GetUserProjectAssocByUserProjRequest, opts ...grpc.CallOption) (*GetUserProjectAssocByUserProjResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProjectAssocByUserProjResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserProjectAssocByUserProj_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) AddUserRole(ctx context.Context, in *AddUserRoleRequest, opts ...grpc.CallOption) (*AddUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserRoleResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserRoleList(ctx context.Context, in *GetUserRoleListRequest, opts ...grpc.CallOption) (*GetUserRoleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRoleListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserRoleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*UpdateUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserRoleResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelUserRoleByIDList(ctx context.Context, in *DelUserRoleByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelUserRoleByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) AddUserRoleAssoc(ctx context.Context, in *AddUserRoleAssocRequest, opts ...grpc.CallOption) (*AddUserRoleAssocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserRoleAssocResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddUserRoleAssoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserRoleAssocList(ctx context.Context, in *GetUserRoleAssocListRequest, opts ...grpc.CallOption) (*GetUserRoleAssocListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRoleAssocListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserRoleAssocList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateUserRoleAssoc(ctx context.Context, in *UpdateUserRoleAssocRequest, opts ...grpc.CallOption) (*UpdateUserRoleAssocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserRoleAssocResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateUserRoleAssoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelUserRoleAssocByIDList(ctx context.Context, in *DelUserRoleAssocByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelUserRoleAssocByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserRoleAssocByUserRole(ctx context.Context, in *GetUserRoleAssocByUserRoleRequest, opts ...grpc.CallOption) (*GetUserRoleAssocByUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRoleAssocByUserRoleResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserRoleAssocByUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) AddUserRolePermissionAssoc(ctx context.Context, in *AddUserRolePermissionAssocRequest, opts ...grpc.CallOption) (*AddUserRolePermissionAssocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserRolePermissionAssocResponse)
	err := c.cc.Invoke(ctx, UserCURD_AddUserRolePermissionAssoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) GetUserRolePermissionAssocList(ctx context.Context, in *GetUserRolePermissionAssocListRequest, opts ...grpc.CallOption) (*GetUserRolePermissionAssocListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRolePermissionAssocListResponse)
	err := c.cc.Invoke(ctx, UserCURD_GetUserRolePermissionAssocList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) UpdateUserRolePermissionAssoc(ctx context.Context, in *UpdateUserRolePermissionAssocRequest, opts ...grpc.CallOption) (*UpdateUserRolePermissionAssocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserRolePermissionAssocResponse)
	err := c.cc.Invoke(ctx, UserCURD_UpdateUserRolePermissionAssoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCURDClient) DelUserRolePermissionAssocByIDList(ctx context.Context, in *DelUserRolePermissionAssocByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserCURD_DelUserRolePermissionAssocByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCURDServer is the server API for UserCURD service.
// All implementations must embed UnimplementedUserCURDServer
// for forward compatibility.
//
// --------------------------------------------------
type UserCURDServer interface {
	// --------------------------------------------------
	// tbl : project
	AddProject(context.Context, *AddProjectRequest) (*AddProjectResponse, error)
	GetProjectList(context.Context, *GetProjectListRequest) (*GetProjectListResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error)
	DelProjectByIDList(context.Context, *DelProjectByIDListRequest) (*Empty, error)
	GetProjectByProjName(context.Context, *GetProjectByProjNameRequest) (*GetProjectByProjNameResponse, error)
	// --------------------------------------------------
	// tbl : user
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	GetUserList(context.Context, *GetUserListRequest) (*GetUserListResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DelUserByIDList(context.Context, *DelUserByIDListRequest) (*Empty, error)
	GetUserByUserName(context.Context, *GetUserByUserNameRequest) (*GetUserByUserNameResponse, error)
	// --------------------------------------------------
	// tbl : user_dept
	AddUserDept(context.Context, *AddUserDeptRequest) (*AddUserDeptResponse, error)
	GetUserDeptList(context.Context, *GetUserDeptListRequest) (*GetUserDeptListResponse, error)
	UpdateUserDept(context.Context, *UpdateUserDeptRequest) (*UpdateUserDeptResponse, error)
	DelUserDeptByIDList(context.Context, *DelUserDeptByIDListRequest) (*Empty, error)
	GetUserDeptByDeptPath(context.Context, *GetUserDeptByDeptPathRequest) (*GetUserDeptByDeptPathResponse, error)
	// --------------------------------------------------
	// tbl : user_dept_assoc
	AddUserDeptAssoc(context.Context, *AddUserDeptAssocRequest) (*AddUserDeptAssocResponse, error)
	GetUserDeptAssocList(context.Context, *GetUserDeptAssocListRequest) (*GetUserDeptAssocListResponse, error)
	UpdateUserDeptAssoc(context.Context, *UpdateUserDeptAssocRequest) (*UpdateUserDeptAssocResponse, error)
	DelUserDeptAssocByIDList(context.Context, *DelUserDeptAssocByIDListRequest) (*Empty, error)
	GetUserDeptAssocByUserDept(context.Context, *GetUserDeptAssocByUserDeptRequest) (*GetUserDeptAssocByUserDeptResponse, error)
	// --------------------------------------------------
	// tbl : user_job
	AddUserJob(context.Context, *AddUserJobRequest) (*AddUserJobResponse, error)
	GetUserJobList(context.Context, *GetUserJobListRequest) (*GetUserJobListResponse, error)
	UpdateUserJob(context.Context, *UpdateUserJobRequest) (*UpdateUserJobResponse, error)
	DelUserJobByIDList(context.Context, *DelUserJobByIDListRequest) (*Empty, error)
	GetUserJobByJobName(context.Context, *GetUserJobByJobNameRequest) (*GetUserJobByJobNameResponse, error)
	// --------------------------------------------------
	// tbl : user_project_assoc
	AddUserProjectAssoc(context.Context, *AddUserProjectAssocRequest) (*AddUserProjectAssocResponse, error)
	GetUserProjectAssocList(context.Context, *GetUserProjectAssocListRequest) (*GetUserProjectAssocListResponse, error)
	UpdateUserProjectAssoc(context.Context, *UpdateUserProjectAssocRequest) (*UpdateUserProjectAssocResponse, error)
	DelUserProjectAssocByIDList(context.Context, *DelUserProjectAssocByIDListRequest) (*Empty, error)
	GetUserProjectAssocByUserProj(context.Context, *GetUserProjectAssocByUserProjRequest) (*GetUserProjectAssocByUserProjResponse, error)
	// --------------------------------------------------
	// tbl : user_role
	AddUserRole(context.Context, *AddUserRoleRequest) (*AddUserRoleResponse, error)
	GetUserRoleList(context.Context, *GetUserRoleListRequest) (*GetUserRoleListResponse, error)
	UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*UpdateUserRoleResponse, error)
	DelUserRoleByIDList(context.Context, *DelUserRoleByIDListRequest) (*Empty, error)
	// --------------------------------------------------
	// tbl : user_role_assoc
	AddUserRoleAssoc(context.Context, *AddUserRoleAssocRequest) (*AddUserRoleAssocResponse, error)
	GetUserRoleAssocList(context.Context, *GetUserRoleAssocListRequest) (*GetUserRoleAssocListResponse, error)
	UpdateUserRoleAssoc(context.Context, *UpdateUserRoleAssocRequest) (*UpdateUserRoleAssocResponse, error)
	DelUserRoleAssocByIDList(context.Context, *DelUserRoleAssocByIDListRequest) (*Empty, error)
	GetUserRoleAssocByUserRole(context.Context, *GetUserRoleAssocByUserRoleRequest) (*GetUserRoleAssocByUserRoleResponse, error)
	// --------------------------------------------------
	// tbl : user_role_permission_assoc
	AddUserRolePermissionAssoc(context.Context, *AddUserRolePermissionAssocRequest) (*AddUserRolePermissionAssocResponse, error)
	GetUserRolePermissionAssocList(context.Context, *GetUserRolePermissionAssocListRequest) (*GetUserRolePermissionAssocListResponse, error)
	UpdateUserRolePermissionAssoc(context.Context, *UpdateUserRolePermissionAssocRequest) (*UpdateUserRolePermissionAssocResponse, error)
	DelUserRolePermissionAssocByIDList(context.Context, *DelUserRolePermissionAssocByIDListRequest) (*Empty, error)
	mustEmbedUnimplementedUserCURDServer()
}

// UnimplementedUserCURDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserCURDServer struct{}

func (UnimplementedUserCURDServer) AddProject(context.Context, *AddProjectRequest) (*AddProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProject not implemented")
}
func (UnimplementedUserCURDServer) GetProjectList(context.Context, *GetProjectListRequest) (*GetProjectListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectList not implemented")
}
func (UnimplementedUserCURDServer) UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedUserCURDServer) DelProjectByIDList(context.Context, *DelProjectByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelProjectByIDList not implemented")
}
func (UnimplementedUserCURDServer) GetProjectByProjName(context.Context, *GetProjectByProjNameRequest) (*GetProjectByProjNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectByProjName not implemented")
}
func (UnimplementedUserCURDServer) AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedUserCURDServer) GetUserList(context.Context, *GetUserListRequest) (*GetUserListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedUserCURDServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserCURDServer) DelUserByIDList(context.Context, *DelUserByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserByIDList not implemented")
}
func (UnimplementedUserCURDServer) GetUserByUserName(context.Context, *GetUserByUserNameRequest) (*GetUserByUserNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByUserName not implemented")
}
func (UnimplementedUserCURDServer) AddUserDept(context.Context, *AddUserDeptRequest) (*AddUserDeptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserDept not implemented")
}
func (UnimplementedUserCURDServer) GetUserDeptList(context.Context, *GetUserDeptListRequest) (*GetUserDeptListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDeptList not implemented")
}
func (UnimplementedUserCURDServer) UpdateUserDept(context.Context, *UpdateUserDeptRequest) (*UpdateUserDeptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserDept not implemented")
}
func (UnimplementedUserCURDServer) DelUserDeptByIDList(context.Context, *DelUserDeptByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserDeptByIDList not implemented")
}
func (UnimplementedUserCURDServer) GetUserDeptByDeptPath(context.Context, *GetUserDeptByDeptPathRequest) (*GetUserDeptByDeptPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDeptByDeptPath not implemented")
}
func (UnimplementedUserCURDServer) AddUserDeptAssoc(context.Context, *AddUserDeptAssocRequest) (*AddUserDeptAssocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserDeptAssoc not implemented")
}
func (UnimplementedUserCURDServer) GetUserDeptAssocList(context.Context, *GetUserDeptAssocListRequest) (*GetUserDeptAssocListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDeptAssocList not implemented")
}
func (UnimplementedUserCURDServer) UpdateUserDeptAssoc(context.Context, *UpdateUserDeptAssocRequest) (*UpdateUserDeptAssocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserDeptAssoc not implemented")
}
func (UnimplementedUserCURDServer) DelUserDeptAssocByIDList(context.Context, *DelUserDeptAssocByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserDeptAssocByIDList not implemented")
}
func (UnimplementedUserCURDServer) GetUserDeptAssocByUserDept(context.Context, *GetUserDeptAssocByUserDeptRequest) (*GetUserDeptAssocByUserDeptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDeptAssocByUserDept not implemented")
}
func (UnimplementedUserCURDServer) AddUserJob(context.Context, *AddUserJobRequest) (*AddUserJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserJob not implemented")
}
func (UnimplementedUserCURDServer) GetUserJobList(context.Context, *GetUserJobListRequest) (*GetUserJobListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserJobList not implemented")
}
func (UnimplementedUserCURDServer) UpdateUserJob(context.Context, *UpdateUserJobRequest) (*UpdateUserJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserJob not implemented")
}
func (UnimplementedUserCURDServer) DelUserJobByIDList(context.Context, *DelUserJobByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserJobByIDList not implemented")
}
func (UnimplementedUserCURDServer) GetUserJobByJobName(context.Context, *GetUserJobByJobNameRequest) (*GetUserJobByJobNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserJobByJobName not implemented")
}
func (UnimplementedUserCURDServer) AddUserProjectAssoc(context.Context, *AddUserProjectAssocRequest) (*AddUserProjectAssocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserProjectAssoc not implemented")
}
func (UnimplementedUserCURDServer) GetUserProjectAssocList(context.Context, *GetUserProjectAssocListRequest) (*GetUserProjectAssocListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjectAssocList not implemented")
}
func (UnimplementedUserCURDServer) UpdateUserProjectAssoc(context.Context, *UpdateUserProjectAssocRequest) (*UpdateUserProjectAssocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserProjectAssoc not implemented")
}
func (UnimplementedUserCURDServer) DelUserProjectAssocByIDList(context.Context, *DelUserProjectAssocByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserProjectAssocByIDList not implemented")
}
func (UnimplementedUserCURDServer) GetUserProjectAssocByUserProj(context.Context, *GetUserProjectAssocByUserProjRequest) (*GetUserProjectAssocByUserProjResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjectAssocByUserProj not implemented")
}
func (UnimplementedUserCURDServer) AddUserRole(context.Context, *AddUserRoleRequest) (*AddUserRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserRole not implemented")
}
func (UnimplementedUserCURDServer) GetUserRoleList(context.Context, *GetUserRoleListRequest) (*GetUserRoleListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRoleList not implemented")
}
func (UnimplementedUserCURDServer) UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*UpdateUserRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedUserCURDServer) DelUserRoleByIDList(context.Context, *DelUserRoleByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserRoleByIDList not implemented")
}
func (UnimplementedUserCURDServer) AddUserRoleAssoc(context.Context, *AddUserRoleAssocRequest) (*AddUserRoleAssocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserRoleAssoc not implemented")
}
func (UnimplementedUserCURDServer) GetUserRoleAssocList(context.Context, *GetUserRoleAssocListRequest) (*GetUserRoleAssocListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRoleAssocList not implemented")
}
func (UnimplementedUserCURDServer) UpdateUserRoleAssoc(context.Context, *UpdateUserRoleAssocRequest) (*UpdateUserRoleAssocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserRoleAssoc not implemented")
}
func (UnimplementedUserCURDServer) DelUserRoleAssocByIDList(context.Context, *DelUserRoleAssocByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserRoleAssocByIDList not implemented")
}
func (UnimplementedUserCURDServer) GetUserRoleAssocByUserRole(context.Context, *GetUserRoleAssocByUserRoleRequest) (*GetUserRoleAssocByUserRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRoleAssocByUserRole not implemented")
}
func (UnimplementedUserCURDServer) AddUserRolePermissionAssoc(context.Context, *AddUserRolePermissionAssocRequest) (*AddUserRolePermissionAssocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserRolePermissionAssoc not implemented")
}
func (UnimplementedUserCURDServer) GetUserRolePermissionAssocList(context.Context, *GetUserRolePermissionAssocListRequest) (*GetUserRolePermissionAssocListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRolePermissionAssocList not implemented")
}
func (UnimplementedUserCURDServer) UpdateUserRolePermissionAssoc(context.Context, *UpdateUserRolePermissionAssocRequest) (*UpdateUserRolePermissionAssocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserRolePermissionAssoc not implemented")
}
func (UnimplementedUserCURDServer) DelUserRolePermissionAssocByIDList(context.Context, *DelUserRolePermissionAssocByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserRolePermissionAssocByIDList not implemented")
}
func (UnimplementedUserCURDServer) mustEmbedUnimplementedUserCURDServer() {}
func (UnimplementedUserCURDServer) testEmbeddedByValue()                  {}

// UnsafeUserCURDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCURDServer will
// result in compilation errors.
type UnsafeUserCURDServer interface {
	mustEmbedUnimplementedUserCURDServer()
}

func RegisterUserCURDServer(s grpc.ServiceRegistrar, srv UserCURDServer) {
	// If the following call panics, it indicates UnimplementedUserCURDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserCURD_ServiceDesc, srv)
}

func _UserCURD_AddProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddProject(ctx, req.(*AddProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetProjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetProjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetProjectList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetProjectList(ctx, req.(*GetProjectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelProjectByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelProjectByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelProjectByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelProjectByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelProjectByIDList(ctx, req.(*DelProjectByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetProjectByProjName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectByProjNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetProjectByProjName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetProjectByProjName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetProjectByProjName(ctx, req.(*GetProjectByProjNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserList(ctx, req.(*GetUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelUserByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelUserByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelUserByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelUserByIDList(ctx, req.(*DelUserByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserByUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserByUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserByUserName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserByUserName(ctx, req.(*GetUserByUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_AddUserDept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserDeptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddUserDept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddUserDept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddUserDept(ctx, req.(*AddUserDeptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserDeptList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDeptListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserDeptList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserDeptList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserDeptList(ctx, req.(*GetUserDeptListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateUserDept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserDeptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateUserDept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateUserDept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateUserDept(ctx, req.(*UpdateUserDeptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelUserDeptByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserDeptByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelUserDeptByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelUserDeptByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelUserDeptByIDList(ctx, req.(*DelUserDeptByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserDeptByDeptPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDeptByDeptPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserDeptByDeptPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserDeptByDeptPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserDeptByDeptPath(ctx, req.(*GetUserDeptByDeptPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_AddUserDeptAssoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserDeptAssocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddUserDeptAssoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddUserDeptAssoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddUserDeptAssoc(ctx, req.(*AddUserDeptAssocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserDeptAssocList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDeptAssocListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserDeptAssocList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserDeptAssocList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserDeptAssocList(ctx, req.(*GetUserDeptAssocListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateUserDeptAssoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserDeptAssocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateUserDeptAssoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateUserDeptAssoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateUserDeptAssoc(ctx, req.(*UpdateUserDeptAssocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelUserDeptAssocByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserDeptAssocByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelUserDeptAssocByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelUserDeptAssocByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelUserDeptAssocByIDList(ctx, req.(*DelUserDeptAssocByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserDeptAssocByUserDept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDeptAssocByUserDeptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserDeptAssocByUserDept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserDeptAssocByUserDept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserDeptAssocByUserDept(ctx, req.(*GetUserDeptAssocByUserDeptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_AddUserJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddUserJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddUserJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddUserJob(ctx, req.(*AddUserJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserJobList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserJobListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserJobList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserJobList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserJobList(ctx, req.(*GetUserJobListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateUserJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateUserJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateUserJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateUserJob(ctx, req.(*UpdateUserJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelUserJobByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserJobByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelUserJobByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelUserJobByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelUserJobByIDList(ctx, req.(*DelUserJobByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserJobByJobName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserJobByJobNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserJobByJobName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserJobByJobName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserJobByJobName(ctx, req.(*GetUserJobByJobNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_AddUserProjectAssoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserProjectAssocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddUserProjectAssoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddUserProjectAssoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddUserProjectAssoc(ctx, req.(*AddUserProjectAssocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserProjectAssocList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectAssocListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserProjectAssocList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserProjectAssocList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserProjectAssocList(ctx, req.(*GetUserProjectAssocListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateUserProjectAssoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProjectAssocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateUserProjectAssoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateUserProjectAssoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateUserProjectAssoc(ctx, req.(*UpdateUserProjectAssocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelUserProjectAssocByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserProjectAssocByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelUserProjectAssocByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelUserProjectAssocByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelUserProjectAssocByIDList(ctx, req.(*DelUserProjectAssocByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserProjectAssocByUserProj_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectAssocByUserProjRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserProjectAssocByUserProj(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserProjectAssocByUserProj_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserProjectAssocByUserProj(ctx, req.(*GetUserProjectAssocByUserProjRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_AddUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddUserRole(ctx, req.(*AddUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserRoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserRoleList(ctx, req.(*GetUserRoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateUserRole(ctx, req.(*UpdateUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelUserRoleByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserRoleByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelUserRoleByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelUserRoleByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelUserRoleByIDList(ctx, req.(*DelUserRoleByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_AddUserRoleAssoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRoleAssocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddUserRoleAssoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddUserRoleAssoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddUserRoleAssoc(ctx, req.(*AddUserRoleAssocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserRoleAssocList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRoleAssocListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserRoleAssocList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserRoleAssocList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserRoleAssocList(ctx, req.(*GetUserRoleAssocListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateUserRoleAssoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleAssocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateUserRoleAssoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateUserRoleAssoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateUserRoleAssoc(ctx, req.(*UpdateUserRoleAssocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelUserRoleAssocByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserRoleAssocByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelUserRoleAssocByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelUserRoleAssocByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelUserRoleAssocByIDList(ctx, req.(*DelUserRoleAssocByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserRoleAssocByUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRoleAssocByUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserRoleAssocByUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserRoleAssocByUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserRoleAssocByUserRole(ctx, req.(*GetUserRoleAssocByUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_AddUserRolePermissionAssoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRolePermissionAssocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).AddUserRolePermissionAssoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_AddUserRolePermissionAssoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).AddUserRolePermissionAssoc(ctx, req.(*AddUserRolePermissionAssocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_GetUserRolePermissionAssocList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRolePermissionAssocListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).GetUserRolePermissionAssocList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_GetUserRolePermissionAssocList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).GetUserRolePermissionAssocList(ctx, req.(*GetUserRolePermissionAssocListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_UpdateUserRolePermissionAssoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRolePermissionAssocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).UpdateUserRolePermissionAssoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_UpdateUserRolePermissionAssoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).UpdateUserRolePermissionAssoc(ctx, req.(*UpdateUserRolePermissionAssocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCURD_DelUserRolePermissionAssocByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserRolePermissionAssocByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCURDServer).DelUserRolePermissionAssocByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCURD_DelUserRolePermissionAssocByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCURDServer).DelUserRolePermissionAssocByIDList(ctx, req.(*DelUserRolePermissionAssocByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCURD_ServiceDesc is the grpc.ServiceDesc for UserCURD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCURD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.userCURD",
	HandlerType: (*UserCURDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProject",
			Handler:    _UserCURD_AddProject_Handler,
		},
		{
			MethodName: "GetProjectList",
			Handler:    _UserCURD_GetProjectList_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _UserCURD_UpdateProject_Handler,
		},
		{
			MethodName: "DelProjectByIDList",
			Handler:    _UserCURD_DelProjectByIDList_Handler,
		},
		{
			MethodName: "GetProjectByProjName",
			Handler:    _UserCURD_GetProjectByProjName_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _UserCURD_AddUser_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _UserCURD_GetUserList_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserCURD_UpdateUser_Handler,
		},
		{
			MethodName: "DelUserByIDList",
			Handler:    _UserCURD_DelUserByIDList_Handler,
		},
		{
			MethodName: "GetUserByUserName",
			Handler:    _UserCURD_GetUserByUserName_Handler,
		},
		{
			MethodName: "AddUserDept",
			Handler:    _UserCURD_AddUserDept_Handler,
		},
		{
			MethodName: "GetUserDeptList",
			Handler:    _UserCURD_GetUserDeptList_Handler,
		},
		{
			MethodName: "UpdateUserDept",
			Handler:    _UserCURD_UpdateUserDept_Handler,
		},
		{
			MethodName: "DelUserDeptByIDList",
			Handler:    _UserCURD_DelUserDeptByIDList_Handler,
		},
		{
			MethodName: "GetUserDeptByDeptPath",
			Handler:    _UserCURD_GetUserDeptByDeptPath_Handler,
		},
		{
			MethodName: "AddUserDeptAssoc",
			Handler:    _UserCURD_AddUserDeptAssoc_Handler,
		},
		{
			MethodName: "GetUserDeptAssocList",
			Handler:    _UserCURD_GetUserDeptAssocList_Handler,
		},
		{
			MethodName: "UpdateUserDeptAssoc",
			Handler:    _UserCURD_UpdateUserDeptAssoc_Handler,
		},
		{
			MethodName: "DelUserDeptAssocByIDList",
			Handler:    _UserCURD_DelUserDeptAssocByIDList_Handler,
		},
		{
			MethodName: "GetUserDeptAssocByUserDept",
			Handler:    _UserCURD_GetUserDeptAssocByUserDept_Handler,
		},
		{
			MethodName: "AddUserJob",
			Handler:    _UserCURD_AddUserJob_Handler,
		},
		{
			MethodName: "GetUserJobList",
			Handler:    _UserCURD_GetUserJobList_Handler,
		},
		{
			MethodName: "UpdateUserJob",
			Handler:    _UserCURD_UpdateUserJob_Handler,
		},
		{
			MethodName: "DelUserJobByIDList",
			Handler:    _UserCURD_DelUserJobByIDList_Handler,
		},
		{
			MethodName: "GetUserJobByJobName",
			Handler:    _UserCURD_GetUserJobByJobName_Handler,
		},
		{
			MethodName: "AddUserProjectAssoc",
			Handler:    _UserCURD_AddUserProjectAssoc_Handler,
		},
		{
			MethodName: "GetUserProjectAssocList",
			Handler:    _UserCURD_GetUserProjectAssocList_Handler,
		},
		{
			MethodName: "UpdateUserProjectAssoc",
			Handler:    _UserCURD_UpdateUserProjectAssoc_Handler,
		},
		{
			MethodName: "DelUserProjectAssocByIDList",
			Handler:    _UserCURD_DelUserProjectAssocByIDList_Handler,
		},
		{
			MethodName: "GetUserProjectAssocByUserProj",
			Handler:    _UserCURD_GetUserProjectAssocByUserProj_Handler,
		},
		{
			MethodName: "AddUserRole",
			Handler:    _UserCURD_AddUserRole_Handler,
		},
		{
			MethodName: "GetUserRoleList",
			Handler:    _UserCURD_GetUserRoleList_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _UserCURD_UpdateUserRole_Handler,
		},
		{
			MethodName: "DelUserRoleByIDList",
			Handler:    _UserCURD_DelUserRoleByIDList_Handler,
		},
		{
			MethodName: "AddUserRoleAssoc",
			Handler:    _UserCURD_AddUserRoleAssoc_Handler,
		},
		{
			MethodName: "GetUserRoleAssocList",
			Handler:    _UserCURD_GetUserRoleAssocList_Handler,
		},
		{
			MethodName: "UpdateUserRoleAssoc",
			Handler:    _UserCURD_UpdateUserRoleAssoc_Handler,
		},
		{
			MethodName: "DelUserRoleAssocByIDList",
			Handler:    _UserCURD_DelUserRoleAssocByIDList_Handler,
		},
		{
			MethodName: "GetUserRoleAssocByUserRole",
			Handler:    _UserCURD_GetUserRoleAssocByUserRole_Handler,
		},
		{
			MethodName: "AddUserRolePermissionAssoc",
			Handler:    _UserCURD_AddUserRolePermissionAssoc_Handler,
		},
		{
			MethodName: "GetUserRolePermissionAssocList",
			Handler:    _UserCURD_GetUserRolePermissionAssocList_Handler,
		},
		{
			MethodName: "UpdateUserRolePermissionAssoc",
			Handler:    _UserCURD_UpdateUserRolePermissionAssoc_Handler,
		},
		{
			MethodName: "DelUserRolePermissionAssocByIDList",
			Handler:    _UserCURD_DelUserRolePermissionAssocByIDList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "z_userService.gen.proto",
}
