// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSheetCeshibiao = "sheet_ceshibiao"

// SheetCeshibiao 192.168.17.29/spcoWylchuWu3/dstaBbsMatBLqc84Bh
type SheetCeshibiao struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	LastEditFrom string `gorm:"column:last_edit_from;not null;comment:ltbl/mtbl, 避免循环触发同步逻辑" json:"last_edit_from"` // ltbl/mtbl, 避免循环触发同步逻辑
	Jingtou      string `gorm:"column:jingtou;not null;comment:source[镜头/SingleText]" json:"jingtou"`               // source[镜头/SingleText]
	Changci      string `gorm:"column:changci;not null;comment:source[场次/SingleText]" json:"changci"`               // source[场次/SingleText]
	Zhuangtai    string `gorm:"column:zhuangtai;not null;comment:source[状态/SingleSelect]" json:"zhuangtai"`         // source[状态/SingleSelect]
}

// TableName SheetCeshibiao's table name
func (*SheetCeshibiao) TableName() string {
	return TableNameSheetCeshibiao
}
