// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRoleAssoc = "user_role_assoc"

// UserRoleAssoc mapped from table <user_role_assoc>
type UserRoleAssoc struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:now()" json:"create_time"`
	CreateUser int32     `gorm:"column:create_user;not null" json:"create_user"`
	UserID     int32     `gorm:"column:user_id;not null" json:"user_id"`
	RoleID     int32     `gorm:"column:role_id;not null" json:"role_id"`
}

// TableName UserRoleAssoc's table name
func (*UserRoleAssoc) TableName() string {
	return TableNameUserRoleAssoc
}
