// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserDept = "user_dept"

// UserDept mapped from table <user_dept>
type UserDept struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:now()" json:"create_time"`
	CreateUser int32     `gorm:"column:create_user;not null" json:"create_user"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:now()" json:"update_time"`
	UpdateUser int32     `gorm:"column:update_user;not null" json:"update_user"`
	DeptPath   string    `gorm:"column:dept_path;not null" json:"dept_path"`
	DeptName   string    `gorm:"column:dept_name;not null" json:"dept_name"`
}

// TableName UserDept's table name
func (*UserDept) TableName() string {
	return TableNameUserDept
}
